package app.yxi.ui

/**
 * 英文译文。**key 就是中文原文**（见 [t]）。
 *
 * ⚠️ 表里查不到的会**原样显示中文** —— 不崩、不空、不冒 key 名。
 * ⚠️ **改了界面上的中文，就要顺手改这里的 key**，否则那句悄悄回落成中文。
 *   `dev/i18n-check.sh` 扫源码里所有 `t("…")` 跟本表比对，就是防这个的。
 * ⚠️ 带占位符的条目，占位符**个数和顺序必须跟中文那条一致** ——
 *   调用方是 `t("…").format(x)`，对不上会抛 MissingFormatArgumentException。
 */
internal object En {
    val map: Map<String, String> = mapOf(
        "语言" to "Language",
        "会话" to "Sessions",
        "主机" to "Hosts",
        "设置" to "Settings",
        "还没有主机" to "No hosts yet",
        "去「主机」那一栏加一台" to "Add one under Hosts",
        "没有可用的认证方式" to "No usable auth method",
        "%s 需要你" to "%s needs you",
        "%s 干完了" to "%s is done",
        "等你决定" to "Waiting on you",
        "连接不在了，没送出去" to "Connection is gone — not sent",
        "提示变了，没有替你按 —— 点开看看" to "The prompt changed — nothing was pressed. Open and look.",
        "送不出去，没批" to "Couldn't send — not approved",
        "盯着 %d 台机器" to "Watching %d host(s)",
        "Claude 需要你时会响" to "You'll be alerted when Claude needs you",
        "Claude 找你" to "Claude wants you",
        "干完了 / 需要你决定" to "Done / needs your call",
        "后台盯梢" to "Background watch",
        "图片%d" to "Image %d",
        "附件%d" to "File %d",
        "等你" to "Waiting on you",
        "干活中" to "Working",
        "已完成" to "Done",
        "空闲" to "Idle",
        "压掉上下文，留个摘要接着聊" to "Compact the context, keep a summary",
        "现在上下文占了多少" to "How much context is used",
        "用量和额度还剩多少" to "Usage and remaining quota",
        "这段会话花了多少" to "What this session cost",
        "清空重开（⚠️ 当前对话就没了）" to "Clear and restart (⚠️ this conversation is gone)",
        "换模型" to "Switch model",
        "版本、账号、连接状态" to "Version, account, connection",
        "看它手头的待办" to "Its current to-dos",
        "退回之前的检查点" to "Rewind to a checkpoint",
        "挑一段历史会话接着聊" to "Resume a past session",
        "管子代理" to "Manage subagents",
        "导出这段对话" to "Export this conversation",
        "改记忆文件" to "Edit memory files",
        "权限规则" to "Permission rules",
        "看 MCP 服务器" to "MCP servers",
        "给这个项目生成 CLAUDE.md" to "Generate CLAUDE.md for this project",
        "审代码" to "Review code",
        "自检安装" to "Check the install",
        "报 bug" to "Report a bug",
        "全部命令" to "All commands",
        " · 排队中" to " · queued",
        "队友消息" to "Teammate message",
        "子 agent 消息" to "Subagent message",
        "跨会话消息" to "Cross-session message",
        "任务通知" to "Task notification",
        "系统提醒" to "System reminder",
        "命令输出" to "Command output",
        "斜杠命令" to "Slash command",
        "这台机器上没放更新包（%s/latest.json 读不到）" to "No update package on this host (can't read %s/latest.json)",
        "更新清单格式不对" to "Malformed update manifest",
        "清单说有 %s，但包不在（%s）" to "Manifest claims %s, but the file isn't there (%s)",
        "连接中…" to "Connecting…",
        "这个会话里没找到 Claude Code 的转录\n（%s）" to "No Claude Code transcript in this session\n(%s)",
        "收不回来：" to "Couldn't pull it back: ",
        "传着…" to "Uploading…",
        "加附件" to "Attach",
        "语音输入" to "Voice input",
        "说吧" to "Go ahead",
        "读不出来了 —— 这张图的授权可能已经失效" to "Can't read it — this image's grant may have expired",
        "说一句…" to "Say something…",
        "已复制" to "Copied",
        "复制整段" to "Copy all",
        "排队中 · 它忙完就轮到这条" to "Queued · runs when it's free",
        "收回改一改" to "Pull back and edit",
        "在忙…" to "Busy…",
        "思考 ▾" to "Thinking ▾",
        "思考 ▸" to "Thinking ▸",
        "左上角送什么键" to "Top-left key",
        "右上角送什么键" to "Top-right key",
        "取消" to "Cancel",
        "…" to "…",
        " · 已截断" to " · truncated",
        "读取中…" to "Reading…",
        "源码" to "Source",
        "阅读" to "Reading",
        "二进制文件，不显示" to "Binary file — not shown",
        "这张图解不开" to "Can't decode this image",
        "找不到 %s" to "Can't find %s",
        "上一级" to "Up",
        "空目录" to "Empty",
        "去不了 %s：" to "Can't go to %s: ",
        "去哪儿" to "Go where",
        "/opt/workspace 或 ~/src" to "/opt/workspace or ~/src",
        "最近" to "Recent",
        "去" to "Go",
        "公钥" to "Public key",
        "还没有主机\n点右上角 ＋ 加一台" to "No hosts yet\nTap ＋ at the top right",
        "⚠️ 地址里有 %s —— 连不上。长按改。" to "⚠️ The address contains %s — can't connect. Long-press to fix.",
        "密钥" to "Key",
        "密码" to "Password",
        "改主机" to "Edit host",
        "加新主机" to "Add host",
        "名字（随便起，只给你自己看）" to "Name (anything — just for you)",
        "IP 或域名，如 38.244.50.31" to "IP or domain, e.g. 38.244.50.31",
        "端口" to "Port",
        " · 用户名 %s" to " · user %s",
        " · 端口 %s" to " · port %s",
        "地址里有个连不上的字符：%s —— 多半是中文输入法打出来的，删掉重打" to "The address has an unusable character: %s — probably from a CJK keyboard. Delete it and retype.",
        "用户名" to "Username",
        "密码（留空 = 不改）" to "Password (blank = unchanged)",
        "密码用设备密钥加密后保存，不落明文。连上后可以一键装公钥，之后免密。" to "The password is sealed with a device key, never stored in plaintext. Once connected you can install the public key and go passwordless.",
        "用 App 自己的 ed25519 密钥。先去右上角「公钥」把它贴进目标机的 authorized_keys。" to "Uses the app's own ed25519 key. Open Public key at the top right and paste it into the host's authorized_keys first.",
        "保存" to "Save",
        "装公钥" to "Install key",
        "再点一次删除" to "Tap again to delete",
        "删除" to "Delete",
        "长按主机就能回到这里。改地址或端口会作废已记住的指纹，下次连接重新确认一次。" to "Long-press a host to get back here. Changing the address or port invalidates the remembered fingerprint — you'll confirm it again next connect.",
        "这台手机的公钥" to "This phone's public key",
        "点一下整块就复制。贴进目标机的 ~/.ssh/authorized_keys（一行）。撤销就删掉那一行，不用改 App 任何设置。" to "Tap the block to copy. Paste it into the host's ~/.ssh/authorized_keys (one line). To revoke, delete that line — nothing to change in the app.",
        "✓ 已复制到剪贴板" to "✓ Copied",
        "点这里复制" to "Tap to copy",
        "指纹 %s" to "Fingerprint %s",
        "复制公钥" to "Copy key",
        "换一把" to "Regenerate",
        "换一把新密钥？" to "Generate a new key?",
        "旧私钥会被丢掉，换不回来。\n\n" to "The old private key is discarded — there's no going back.\n\n",
        "所有已经装过旧公钥的服务器都会立刻连不上，" to "Every host holding the old public key stops working immediately; ",
        "要么重新装一次新公钥，要么手工删掉 authorized_keys 里那行 yxi@android。\n\n" to "either install the new key again, or remove the yxi@android line from authorized_keys by hand.\n\n",
        "只有在怀疑私钥泄露、或想换台手机重来时才需要这么做。" to "Only do this if you think the private key leaked, or you're starting over on a new phone.",
        "换" to "Regenerate",
        "算了" to "Never mind",
        "用密码连一次，把这台手机的公钥追加进 ~/.ssh/authorized_keys，之后就免密了。相当于 ssh-copy-id。" to "Connects once with the password and appends this phone's public key to ~/.ssh/authorized_keys — passwordless afterwards. Same as ssh-copy-id.",
        "建不了连接" to "Couldn't build a connection",
        "✅ 装好了（authorized_keys 里现有 %s 行 yxi 公钥），已切到密钥认证" to "✅ Installed (%s yxi key line(s) now in authorized_keys) — switched to key auth",
        "处理中…" to "Working…",
        "连接并安装" to "Connect and install",
        "还要放行后台运行" to "Background also needs allowing",
        "这台机器上的 Claude 需要你时，手机靠一条常驻连接来响。\n\n" to "When Claude on this host needs you, the phone relies on one long-lived connection to ring.\n\n",
        "系统的省电优化会把它掐掉 —— 荣耀 / 华为 尤其狠，" to "Battery optimisation will kill it — Honor and Huawei especially, ",
        "而且掐掉之后不会有任何提示，你只会觉得「怎么不响了」。\n\n" to "and you get no warning at all; it just stops ringing.\n\n",
        "去设置里把 Yxi 设成「允许后台活动 / 不受限制」。" to "Set Yxi to Unrestricted / allow background activity in system settings.",
        "去设置" to "Open settings",
        "知道了" to "Got it",
        "整行" to "Whole line",
        "逐键" to "Per key",
        "历史" to "History",
        "悬浮" to "Cards",
        "文件" to "Files",
        "终端" to "Terminal",
        "↓ 下拉重连" to "↓ Pull to reconnect",
        "置顶" to "Pin",
        "已连" to "Connected",
        "回它一句" to "Reply",
        "开终端" to "Terminal",
        "不用先 attach —— 直接送进那个会话（tmux send-keys）。" to "No attach needed — goes straight into that session (tmux send-keys).",
        "发送" to "Send",
        "这个 App" to "This app",
        "查着…" to "Checking…",
        "检查更新" to "Check for updates",
        "还没有主机 —— 更新包放在你自己的服务器上，得先加一台才能查。" to "No hosts yet — the update package lives on your own server, so add one first.",
        "贴进目标机的 ~/.ssh/authorized_keys 就能免密连。撤销 = 删掉那一行。" to "Paste it into the host's ~/.ssh/authorized_keys for passwordless login. To revoke, delete that line.",
        "查看 / 复制 / 换一把" to "View / copy / regenerate",
        "手机主动响" to "Ringing on your phone",
        "盯着的机器" to "Hosts watched",
        "%d 台" to "%d host(s)",
        "⚠️ 一台都没开 —— 前面两项放行了也不会响。" to "⚠️ None are on — the two items above won't make it ring by themselves. ",
        "去「主机」那一栏，点每台机器右边的铃铛把它打开。" to "Go to Hosts and tap the bell next to a machine.",
        "只通知置顶的会话" to "Only notify pinned sessions",
        "现在是**每个**会话都会响。会话多的时候通知栏会很吵。" to "Right now **every** session rings. With many sessions that gets noisy.",
        "⚠️ 一条都没置顶 —— 现在等于全部通知。" to "⚠️ Nothing is pinned — so this currently notifies everything. ",
        "去会话列表点卡片右上角的图钉，置顶几个你真正在等的。" to "Pin the ones you're actually waiting on, from the pin at the top right of a card.",
        "只有置顶的 %d 个会响，其余的静悄悄干活。" to "Only the %d pinned one(s) ring; the rest work quietly. ",
        "置顶在会话列表里点卡片右上角的图钉。" to "Pin from the top right of a session card.",
        "通知权限" to "Notification permission",
        "后台不受限制" to "Unrestricted background",
        "荣耀/华为还有一道单独的开关：设置 → 应用和服务 → 应用启动管理 → " to "Honor/Huawei has one more switch: Settings → Apps → App launch → ",
        "找到 Yxi → 关掉「自动管理」，然后三项（自启动/关联启动/后台活动）全打开。" to "find Yxi → turn off Manage automatically, then enable all three (auto-launch, secondary launch, background activity).",
        "缺任何一项，Claude 需要你时手机都不会响，而且不会有任何提示。" to "Miss any one of these and the phone stays silent when Claude needs you — with no warning.",
        "荣耀 / 华为 的后台管控尤其狠。" to "Honor and Huawei are especially aggressive about background apps.",
        "关于" to "About",
        "Yxi —— 手机上的 Claude Code 指挥台。\n" to "Yxi — a Claude Code console on your phone.\n",
        "全部走 SSH：不开新端口、不要证书、不经过任何第三方服务器。\n" to "Everything goes over SSH: no new ports, no certificates, no third-party servers.\n",
        "服务器上唯一需要装的是 yxi-hook（就为了让手机能主动响）。" to "The only thing to install on the server is yxi-hook — purely so the phone can ring.",
        "开发者模式" to "Developer mode",
        "口令" to "Passphrase",
        "口令不对" to "Wrong passphrase",
        "进" to "Enter",
        "开发者" to "Developer",
        "诊断会把整条连接路径一步步走一遍：解析地址 → 连 TCP → SSH 招呼 → 认证，" to "Diagnostics walks the whole path: resolve → TCP → SSH banner → auth, ",
        "再挨个试同一个 IP 上的几个端口。里面不含密码和私钥，可以直接贴出来。\n" to "then probes a few ports on the same IP. It contains no passwords or private keys — safe to paste.\n",
        "测的是 " to "Testing ",
        "（还没有主机）" to "(no hosts yet)",
        " —— 要换一台就去「会话」页顶部切换。" to " — switch hosts from the top of the Sessions page.",
        "测着…（约 30 秒）" to "Testing… (about 30s)",
        "跑一次诊断" to "Run diagnostics",
        "复制" to "Copy",
        "再连点三下版本号 = 退出开发者模式。" to "Triple-tap the version again to leave developer mode.",
        "已放行" to "Allowed",
        "去开启" to "Turn on",
        "第一次连这台主机" to "First time connecting to this host",
        "\n\n指纹\n" to "\n\nFingerprint\n",
        "\n\n请核对它跟服务器上 ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub " to "\n\nCheck it matches ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub ",
        "的输出一致。不一致就别连。" to "on the server. If it differs, don't connect.",
        "指纹对得上，连" to "Fingerprint matches — connect",
        "⚠️ 主机指纹变了，已拒绝连接。真是重装了就把这台主机删掉重加。" to "⚠️ The host fingerprint changed — connection refused. If it really was reinstalled, delete this host and add it again.",
        "地址解析不了：「%s」\n" to "Can't resolve the address: \"%s\"\n",
        "里面有个连不上的字符 %s —— 多半是中文输入法打的，删掉用英文键盘重打。" to "It contains an unusable character %s — probably typed with a CJK keyboard. Delete it and retype on an English one.",
        "这一栏要填 IP 或真实域名。手机上没有 ~/.ssh/config，" to "This field wants an IP or a real domain. There's no ~/.ssh/config on a phone, ",
        "SSH 别名（station 之类）在这儿用不了；也别带 http:// 或路径。" to "so SSH aliases (like \"station\") don't work here — and don't include http:// or a path.",
        "认证被拒：密码不对，或这台机器的 authorized_keys 里没有这把公钥。" to "Auth rejected: wrong password, or this key isn't in the host's authorized_keys.",
        "你取消了指纹确认，所以没连。" to "You cancelled the fingerprint check, so nothing connected.",
        "这台主机还没有可用的认证方式" to "This host has no usable auth method yet",
        "连接断了，正在重连…" to "Connection dropped — reconnecting…",
        "连接掉了，自动重连" to "Connection dropped, reconnecting",
        "归档的会话" to "Archived sessions",
        "没有归档的会话" to "Nothing archived",
        "没有会话" to "No sessions",
        "上滑取消归档 · 长按结束会话" to "Swipe up to unarchive · long-press to end",
        "上滑归档（不杀会话）· 长按结束会话" to "Swipe up to archive (session keeps running) · long-press to end",
        "会执行 tmux kill-session —— 那个会话里正在跑的东西**会被中断**，" to "This runs tmux kill-session — whatever that session is doing **gets interrupted**, ",
        "没保存的内容没了，取消不了。\n\n" to "unsaved work is lost, and it can't be undone.\n\n",
        "只是不想在列表里看见它的话，上滑归档就行，那个不动服务器。" to "If you just don't want it in the list, swipe up to archive — that touches nothing on the server.",
        "结束" to "End",
        "当前" to "Current",
        "已归档" to "Archived",
        "出错" to "Failed",
        "完成" to "Done",
        "进行中" to "Running",
        "覆盖已有文件" to "Overwrote existing file",
        "图片 " to "Image ",
        "后台跑" to "In background",
        "你拒绝了" to "You declined",
        "计划被否了" to "Plan rejected",
        "计划" to "Plan",
        "等你选（可多选）" to "Waiting on you (multi-select)",
        "等你选" to "Waiting on you",
        "提交" to "Submit",
        "下载并安装" to "Download and install",
        "以后" to "Later",
        "先在设置里允许本应用安装，然后再点一次" to "Allow installs from this app in settings, then tap again",
        "5 小时窗口" to "5-hour window",
        "对话" to "Chat",
        "没有指定会话" to "No session given",
        "这个会话里没跑过 Claude Code" to "Claude Code has never run in this session",
        "还没有置顶的会话" to "Nothing pinned yet",
        "全部会话…" to "All sessions…",
        "听到的是这句" to "Heard this",
        "确认后会原样打进终端并回车。识别错了就取消重说。" to "On confirm this is typed into the terminal verbatim and Enter is pressed. If it misheard, cancel and try again.",
        "发进终端" to "Send to terminal",
        "对话模式用不了" to "Chat mode unavailable",
        "。\n\n对话模式渲染的是 Claude Code 的转录文件；这个会话里没有，所以没东西可显示。终端和文件模式照常可用。" to ".\n\nChat mode renders Claude Code's transcript file; this session has none, so there's nothing to show. Terminal and Files still work.",
        "历史模式 · 上下滑动翻页 · 再点「历史」退出" to "History mode · swipe to page · tap History again to exit",
        "没有这个文件或目录" to "No such file or directory",
        "没有权限" to "Permission denied",
        "%d 项" to "%d items",
        "保存时会拆成：地址 %s" to "On save this splits into: host %s",
        "生成失败：%s: %s" to "Generation failed: %s: %s",
        "给 %s 装公钥" to "Install key on %s",
        "刷新失败：%s" to "Refresh failed: %s",
        "%d 个会话 · 点读对话 · 长按发消息" to "%d sessions · tap to read · long-press to send",
        "发给 %s" to "Send to %s",
        "版本 %s" to "Version %s",
        "连不上 %s，没查成" to "Can't reach %s — check didn't run",
        "查的时候出错：%s" to "Error while checking: %s",
        "✓ 已是最新（服务器上就是 %s）" to "✓ Up to date (the server has %s)",
        "✗ 没查到：%s" to "✗ Not found: %s",
        "有新版本 %s · %s" to "New version %s · %s",
        "连不上 %s：%s\n检查 IP、端口，以及服务器是否开着。" to "Can't reach %s: %s\nCheck the IP, the port, and that the server is up.",
        "连不上：%s: %s" to "Can't connect: %s: %s",
        "归档 %d" to "Archived %d",
        "结束会话 %s？" to "End session %s?",
        "…还有 %d 行" to "…%d more lines",
        "有新版本 %s" to "New version %s",
        "下载失败：%s" to "Download failed: %s",
        "下载不完整（%d/%d），没装" to "Incomplete download (%d/%d) — not installed",
        "拉不起安装器：%s" to "Couldn't launch the installer: %s",
        "剩 %s" to "%s left",
        " · %dh 前" to " · %dh ago",
        "距重置 %s" to "%s to reset",
        " · %d/分" to " · %d/min",
        "终端起不来：%s" to "Terminal won't start: %s",
        "切不过去：%s" to "Couldn't switch: %s",
        "%d 个会话等你" to "%d session(s) waiting on you",
        "上下文 %s" to "context %s",
        "今日 %s · %s" to "today %s · %s",
        "没有闲着的会话可以借来查额度 —— 等它忙完再点" to "No idle session to borrow for the quota check — try again when one frees up",
        " 重置" to " reset",
        "额度" to "Quota",
        "问一下这台机器…" to "asking this host…",
        "5 小时额度" to "5-hour quota",
        "本周额度" to "This week",
        "点一下查" to "tap to check",
        "窗口已过" to "Window elapsed",
        "开选单…" to "opening…",
        "它正忙着，或者输入框里有没发完的字 —— 等一下再点" to "It's busy, or there's unsent text in its input box — try again in a moment",
        "同时设为默认（以后新开的会话都用它）" to "Also set as default (every new session will use it)",
        "不勾的话只换这个会话，别的会话和默认都不动。" to "Unchecked, this changes only this session — other sessions and the default stay put.",
        "界面风格" to "Look",
        "⚠️ 终端永远是深底 —— 彩色输出在浅底上读不了。所以浅色风格下切到终端会亮暗跳一下。" to "⚠️ The terminal stays dark — coloured output is unreadable on a light background. So on the light look, switching to the terminal jumps in brightness.",
        "已用 %d%% · 剩 %d%%" to "%d%% used · %d%% left",
        "5 小时" to "5-hour",
        "本周" to "Week",
        "%d 分钟前查的" to "checked %dm ago",
        "%d 小时前查的" to "checked %dh ago",
        "这个文件读不出来 —— 换一张试试" to "Can't read this file — try another",
        "开不了 SFTP 通道" to "Couldn't open an SFTP channel",
        "传失败：%s" to "Upload failed: %s",
    )
}
