package app.yxi.ui

/**
 * 英文译文。**key 就是中文原文**（见 [t]）。
 *
 * ⚠️ 表里查不到的会**原样显示中文** —— 不崩、不空、不冒 key 名。
 * ⚠️ **改了界面上的中文，就要顺手改这里的 key**，否则那句悄悄回落成中文。
 *   `dev/i18n-check.sh` 扫源码里所有 `t("…")` 跟本表比对，就是防这个的。
 * ⚠️ 带占位符的条目，占位符**个数和顺序必须跟中文那条一致** ——
 *   调用方是 `t("…").format(x)`，对不上会抛 MissingFormatArgumentException。
 */
internal object En {
    val map: Map<String, String> = mapOf(
        "语言" to "Language",
        "包对不上（校验失败），没装 —— 换个网络再试一次" to "Checksum mismatch — not installed. Try another network.",
        "这个包的签名跟本机不一致，没装" to "That package is signed by someone else — not installed.",
        "免费档最多绑 2 台" to "Free plan: up to 2 hosts",
        "再加就要 Pro 或 Ultra —— 它们不限台数。\n（主机和密钥一直只存在这台手机上，这条限制也只在手机上判。）" to "Pro or Ultra removes the limit.\n(Hosts and keys never leave this phone — this check runs on the phone too.)",
        "这个账号被封禁了" to "This account is banned",
        "原因：%s" to "Reason: %s",
        "未说明" to "not stated",
        "到 %s" to "until %s",
        "永久" to "permanent",
        "封禁期间改不了资料、也兑不了码。" to "While banned you can't edit your profile or redeem codes.",
        "怎么买" to "How to buy",
        "去商店买" to "Buy in the shop",
        "加微信买" to "Buy via WeChat",
        "收起微信" to "Hide WeChat",
        "二维码加载中…" to "Loading QR…",
        "微信号 %s（%s）· 长按复制" to "WeChat %s (%s) · tap to copy",
        "微信号复制好了" to "WeChat ID copied",
        "买到兑换码之后，回来在上面输入就能开通。" to "Buy a code, then enter it above to activate.",
        "你选了「手机上算」，但模型还没下 —— 去「我的 · 语音识别」下一个" to "You picked on-device, but the model isn't downloaded — get it under Profile · Voice input",
        "你选了「服务器上算」，但这台机器上没有 yxi-asr" to "You picked server-side, but this machine has no yxi-asr",
        "自动" to "Auto",
        "手机上算" to "On this phone",
        "服务器上算" to "On your server",
        "系统识别" to "System",
        "自动：手机上下了模型就用手机（离线、最快），没下就用服务器上的 `yxi-asr`，都没有才退回系统识别。" to "Auto: use the phone if the model is downloaded (offline, fastest), else `yxi-asr` on your server, else the system recogniser.",
        "手机上算：不联网、不经过任何服务器。要先下模型（约 %d MB）。" to "On this phone: offline, never leaves the device. Needs the model (~%d MB).",
        "服务器上算：同一个模型跑在你自己的机器上，最准。要那台机器装过 `yxi-asr`（装机脚本里有）。" to "On your server: same model on a real machine — most accurate. Needs `yxi-asr` installed there.",
        "系统识别：不占空间，但依赖 Google 服务 —— 关了 GMS 的手机上它是不存在的。" to "System: no download, but needs Google services — absent on phones with GMS disabled.",
        "模型是开源的 SenseVoice，中英粤日都认、自带标点。" to "The model is the open-source SenseVoice: Chinese, English, Cantonese and Japanese, with punctuation.",
        "在用" to "In use",
        "UID 复制好了" to "UID copied",
        "语音识别就绪：点一下麦克风开始说，再点一下结束" to "Voice input ready: tap the mic to start, tap again to stop",
        "反馈与版本" to "Feedback & version",
        "我的" to "Profile",
        "手机功能" to "On this phone",
        "界面" to "Appearance",
        "关于与帮助" to "About & help",
        "太短了，没录到东西" to "Too short — nothing recorded",
        "点这里登录" to "Tap to sign in",
        "登录好了" to "Signed in",
        "退出登录" to "Sign out",
        "未登录" to "Not signed in",
        "还没登录" to "Not signed in yet",
        "登录后才能看会员状态" to "Sign in to see your membership",
        "还没登录 —— 现在改只存在这台手机上" to "Not signed in — changes stay on this phone",
        "1–24 个字" to "1–24 characters",
        "最多 60 个字" to "60 characters max",
        "这个月还能改 %d 次" to "%d edits left this month",
        "这个月还能改 %d 次资料" to "%d profile edits left this month",
        "%s 恢复" to "resets %s",
        "改多少次都行" to "Unlimited edits",
        "资料改多少次都行" to "Unlimited profile edits",
        "兑换码" to "Redeem code",
        "兑换" to "Redeem",
        "兑换中…" to "Redeeming…",
        "先登录再兑换" to "Sign in first",
        "当前：%s · 永久" to "Current: %s · never expires",
        "当前：%s · %s 到期" to "Current: %s · expires %s",
        "当前：%s" to "Current: %s",
        "资料每月能改 1 次" to "1 profile edit per month",
        "资料每月能改 2 次" to "2 profile edits per month",
        "还不能直接买 —— 先用兑换码。价格定了会在这儿开。" to "No purchases yet — use a redeem code. Pricing lands here later.",
        "取消置顶" to "Unpin",
        "这是上次的内容，正在取最新…" to "Showing the last snapshot — fetching the latest…",
        "点这里起个名" to "Tap to set a name",
        "写句个性签名" to "Add a status",
        "会员中心" to "Membership",
        "夜间" to "Dark",
        "我" to "Me",
        "点头像换一张" to "Tap the avatar to change it",
        "昵称" to "Name",
        "个性签名" to "Status",
        "还没设昵称" to "No name yet",
        "当前：免费版" to "Current: Free",
        "当前：Pro" to "Current: Pro",
        "当前：Ultra" to "Current: Ultra",
        "免费版" to "Free",
        "一台机器，够用" to "One machine, and it works",
        "1 台主机" to "1 host",
        "会话看板 + 对话 + 终端" to "Board, chat and terminal",
        "本机语音转写" to "On-device voice input",
        "多机器盯梢，随手就批" to "Watch every machine, approve from anywhere",
        "主机不限台" to "Unlimited hosts",
        "后台盯梢 + 通知里直接批" to "Background watch, approve from the notification",
        "实验室：让 agent 画图" to "Lab: let the agent draw",
        "分组与组规同步" to "Groups and group rules, synced",
        "整队 agent 一起带" to "Run a whole crew of agents",
        "Pro 的全部" to "Everything in Pro",
        "多设备同步" to "Sync across devices",
        "实验室额度更高" to "Higher Lab quota",
        "优先支持" to "Priority support",
        "订阅还没开放 —— 先把两档能有什么摆在这儿，价格定了再说。" to "Subscriptions aren't open yet — here's what each tier will include; pricing comes later.",
        "即将开放" to "Coming soon",
        "会话" to "Sessions",
        "主机" to "Hosts",
        "设置" to "Settings",
        "还没有主机" to "No hosts yet",
        "去「主机」那一栏加一台" to "Add one under Hosts",
        "没有可用的认证方式" to "No usable auth method",
        "%s 需要你" to "%s needs you",
        "%s 干完了" to "%s is done",
        "等你决定" to "Waiting on you",
        "连接不在了，没送出去" to "Connection is gone — not sent",
        "提示变了，没有替你按 —— 点开看看" to "The prompt changed — nothing was pressed. Open and look.",
        "送不出去，没批" to "Couldn't send — not approved",
        "盯着 %d 台机器" to "Watching %d host(s)",
        "Claude 需要你时会响" to "You'll be alerted when Claude needs you",
        "Claude 找你" to "Claude wants you",
        "干完了 / 需要你决定" to "Done / needs your call",
        "后台盯梢" to "Background watch",
        "图片%d" to "Image %d",
        "附件%d" to "File %d",
        "等你" to "Waiting on you",
        "干活中" to "Working",
        "已完成" to "Done",
        "空闲" to "Idle",
        "压掉上下文，留个摘要接着聊" to "Compact the context, keep a summary",
        "现在上下文占了多少" to "How much context is used",
        "用量和额度还剩多少" to "Usage and remaining quota",
        "这段会话花了多少" to "What this session cost",
        "清空重开（⚠️ 当前对话就没了）" to "Clear and restart (⚠️ this conversation is gone)",
        "换模型" to "Switch model",
        "版本、账号、连接状态" to "Version, account, connection",
        "看它手头的待办" to "Its current to-dos",
        "退回之前的检查点" to "Rewind to a checkpoint",
        "挑一段历史会话接着聊" to "Resume a past session",
        "管子代理" to "Manage subagents",
        "导出这段对话" to "Export this conversation",
        "改记忆文件" to "Edit memory files",
        "权限规则" to "Permission rules",
        "看 MCP 服务器" to "MCP servers",
        "给这个项目生成 CLAUDE.md" to "Generate CLAUDE.md for this project",
        "审代码" to "Review code",
        "自检安装" to "Check the install",
        "报 bug" to "Report a bug",
        "全部命令" to "All commands",
        " · 排队中" to " · queued",
        "队友消息" to "Teammate message",
        "子 agent 消息" to "Subagent message",
        "跨会话消息" to "Cross-session message",
        "任务通知" to "Task notification",
        "系统提醒" to "System reminder",
        "命令输出" to "Command output",
        "斜杠命令" to "Slash command",
        "这台机器上没放更新包（%s/latest.json 读不到）" to "No update package on this host (can't read %s/latest.json)",
        "更新清单格式不对" to "Malformed update manifest",
        "清单说有 %s，但包不在（%s）" to "Manifest claims %s, but the file isn't there (%s)",
        "连接中…" to "Connecting…",
        "这个会话里没找到 Claude Code 的转录\n（%s）" to "No Claude Code transcript in this session\n(%s)",
        "收不回来：" to "Couldn't pull it back: ",
        "传着…" to "Uploading…",
        "加附件" to "Attach",
        "语音输入" to "Voice input",
        "说吧" to "Go ahead",
        "读不出来了 —— 这张图的授权可能已经失效" to "Can't read it — this image's grant may have expired",
        "说一句…" to "Say something…",
        "已复制" to "Copied",
        "复制整段" to "Copy all",
        "排队中 · 它忙完就轮到这条" to "Queued · runs when it's free",
        "收回改一改" to "Pull back and edit",
        "在忙…" to "Busy…",
        "思考 ▾" to "Thinking ▾",
        "思考 ▸" to "Thinking ▸",
        "左上角送什么键" to "Top-left key",
        "右上角送什么键" to "Top-right key",
        "取消" to "Cancel",
        "…" to "…",
        " · 已截断" to " · truncated",
        "读取中…" to "Reading…",
        "源码" to "Source",
        "阅读" to "Reading",
        "二进制文件，不显示" to "Binary file — not shown",
        "这张图解不开" to "Can't decode this image",
        "找不到 %s" to "Can't find %s",
        "上一级" to "Up",
        "空目录" to "Empty",
        "去不了 %s：" to "Can't go to %s: ",
        "去哪儿" to "Go where",
        "/opt/workspace 或 ~/src" to "/opt/workspace or ~/src",
        "最近" to "Recent",
        "去" to "Go",
        "公钥" to "Public key",
        "还没有主机\n点右上角 ＋ 加一台" to "No hosts yet\nTap ＋ at the top right",
        "⚠️ 地址里有 %s —— 连不上。长按改。" to "⚠️ The address contains %s — can't connect. Long-press to fix.",
        "密钥" to "Key",
        "密码" to "Password",
        "改主机" to "Edit host",
        "加新主机" to "Add host",
        "名字（随便起，只给你自己看）" to "Name (anything — just for you)",
        "IP 或域名，如 38.244.50.31" to "IP or domain, e.g. 38.244.50.31",
        "端口" to "Port",
        " · 用户名 %s" to " · user %s",
        " · 端口 %s" to " · port %s",
        "地址里有个连不上的字符：%s —— 多半是中文输入法打出来的，删掉重打" to "The address has an unusable character: %s — probably from a CJK keyboard. Delete it and retype.",
        "用户名" to "Username",
        "密码（留空 = 不改）" to "Password (blank = unchanged)",
        "密码用设备密钥加密后保存，不落明文。连上后可以一键装公钥，之后免密。" to "The password is sealed with a device key, never stored in plaintext. Once connected you can install the public key and go passwordless.",
        "用 App 自己的 ed25519 密钥。先去右上角「公钥」把它贴进目标机的 authorized_keys。" to "Uses the app's own ed25519 key. Open Public key at the top right and paste it into the host's authorized_keys first.",
        "保存" to "Save",
        "装公钥" to "Install key",
        "再点一次删除" to "Tap again to delete",
        "删除" to "Delete",
        "长按主机就能回到这里。改地址或端口会作废已记住的指纹，下次连接重新确认一次。" to "Long-press a host to get back here. Changing the address or port invalidates the remembered fingerprint — you'll confirm it again next connect.",
        "这台手机的公钥" to "This phone's public key",
        "点一下整块就复制。贴进目标机的 ~/.ssh/authorized_keys（一行）。撤销就删掉那一行，不用改 App 任何设置。" to "Tap the block to copy. Paste it into the host's ~/.ssh/authorized_keys (one line). To revoke, delete that line — nothing to change in the app.",
        "✓ 已复制到剪贴板" to "✓ Copied",
        "点这里复制" to "Tap to copy",
        "指纹 %s" to "Fingerprint %s",
        "复制公钥" to "Copy key",
        "换一把" to "Regenerate",
        "换一把新密钥？" to "Generate a new key?",
        "旧私钥会被丢掉，换不回来。\n\n" to "The old private key is discarded — there's no going back.\n\n",
        "所有已经装过旧公钥的服务器都会立刻连不上，" to "Every host holding the old public key stops working immediately; ",
        "要么重新装一次新公钥，要么手工删掉 authorized_keys 里那行 yxi@android。\n\n" to "either install the new key again, or remove the yxi@android line from authorized_keys by hand.\n\n",
        "只有在怀疑私钥泄露、或想换台手机重来时才需要这么做。" to "Only do this if you think the private key leaked, or you're starting over on a new phone.",
        "换" to "Regenerate",
        "算了" to "Never mind",
        "用密码连一次，把这台手机的公钥追加进 ~/.ssh/authorized_keys，之后就免密了。相当于 ssh-copy-id。" to "Connects once with the password and appends this phone's public key to ~/.ssh/authorized_keys — passwordless afterwards. Same as ssh-copy-id.",
        "建不了连接" to "Couldn't build a connection",
        "✅ 装好了（authorized_keys 里现有 %s 行 yxi 公钥），已切到密钥认证" to "✅ Installed (%s yxi key line(s) now in authorized_keys) — switched to key auth",
        "处理中…" to "Working…",
        "连接并安装" to "Connect and install",
        "还要放行后台运行" to "Background also needs allowing",
        "这台机器上的 Claude 需要你时，手机靠一条常驻连接来响。\n\n" to "When Claude on this host needs you, the phone relies on one long-lived connection to ring.\n\n",
        "系统的省电优化会把它掐掉 —— 荣耀 / 华为 尤其狠，" to "Battery optimisation will kill it — Honor and Huawei especially, ",
        "而且掐掉之后不会有任何提示，你只会觉得「怎么不响了」。\n\n" to "and you get no warning at all; it just stops ringing.\n\n",
        "去设置里把 Yxi 设成「允许后台活动 / 不受限制」。" to "Set Yxi to Unrestricted / allow background activity in system settings.",
        "去设置" to "Open settings",
        "知道了" to "Got it",
        "整行" to "Whole line",
        "逐键" to "Per key",
        "历史" to "History",
        "悬浮" to "Cards",
        "文件" to "Files",
        "终端" to "Terminal",
        "↓ 下拉重连" to "↓ Pull to reconnect",
        "置顶" to "Pin",
        "已连" to "Connected",
        "回它一句" to "Reply",
        "开终端" to "Terminal",
        "不用先 attach —— 直接送进那个会话（tmux send-keys）。" to "No attach needed — goes straight into that session (tmux send-keys).",
        "发送" to "Send",
        "这个 App" to "This app",
        "查着…" to "Checking…",
        "复制路径" to "Copy path",
        "路径已复制" to "Path copied",
        "再建一个「%s」" to "Also create \"%s\"",
        "它是收藏的 —— 杀掉后会进「未启用」，随时点一下就能在原目录拉回来。" to "It's a favourite — after this it moves to Dormant, one tap brings it back in the same directory.",
        "取消收藏" to "Unfavourite",
        "收藏" to "Favourite",
        "未启用" to "Dormant",
        "在拉起 %s…" to "Starting %s…",
        "拉不起来：%s" to "Couldn't start it: %s",
        "终止 %s？" to "Terminate %s?",
        "会话连同里面跑着的 Claude 一起结束，占的内存放出来。转录文件留着，不会删。" to "The session and the Claude running inside it both end, freeing the memory. The transcript is kept.",
        "⚠️ 它**正在干活**，现在杀会丢掉这一轮还没写完的东西。" to "⚠️ It is **working right now** — killing it loses whatever this turn hasn't written yet.",
        "⚠️ 它正在等你回答，杀掉这个问题就没了。" to "⚠️ It is **waiting for your answer** — killing it discards the question.",
        "终止失败 —— 会话可能已经没了" to "Couldn't terminate — the session may already be gone",
        "终止" to "Terminate",
        "不知道原来在哪个目录，会开在 ~" to "Directory unknown — it will start in ~",
        "唤起" to "Wake",
        "可以收拾 %d 类 · 约 %d MB" to "%d kinds to clean up · about %d MB",
        "挑要收拾的" to "Pick what to clean up",
        "%d 个 · %d MB · 最久跑了 %d 分钟" to "%d of them · %d MB · oldest running %d min",
        "先勾几个" to "Tick something first",
        "收拾 %d 个 · %d MB" to "Clean up %d · %d MB",
        "安装器拉起来了" to "Installer opened",
        "装不上" to "Couldn't install",
        "装上" to "Install",
        "读不出这台机器的状态（不是 Linux？）" to "Can't read this machine's state (not Linux?)",
        "体检失败：%s" to "Health check failed: %s",
        "松快" to "Comfortable",
        "有点紧" to "A bit tight",
        "很吃力" to "Struggling",
        "快扛不住了" to "About to fall over",
        "负载 %.1f/%d核 · 内存 %d%% · 交换 %d%% · 被抢 %d%% · 盘 %d%%" to "load %.1f/%d cores · mem %d%% · swap %d%% · stolen %d%% · disk %d%%",
        "（机器里面修不了，得找服务商）" to " (can't be fixed from inside — talk to your provider)",
        "收拾中…" to "Cleaning up…",
        "一键收拾 · %d 项 · 约 %d MB" to "Clean up %d things · about %d MB",
        "要收拾这些" to "These will be cleaned up",
        "缓存和跑飞的进程收掉不丢东西。会话那一类会真的关掉 —— 但对话存档留着，之后还能接回来。" to "Caches and runaway processes are safe to clear. Sessions really do get closed — but their transcripts stay, so you can resume them later.",
        "· %s · %d MB · 跑了 %d 分钟" to "· %s · %d MB · running %d min",
        "⚠️ 这台机器有 %d%% 的 CPU 被宿主机抢走了 —— 那个收拾不掉，得让服务商迁移实例。" to "⚠️ %d%% of this machine's CPU is being taken by the hypervisor — cleaning up won't help; ask your provider to migrate the instance.",
        "收拾" to "Clean up",
        "CPU 被宿主机抢走 %d%% —— 这台云主机所在的物理机严重超卖" to "%d%% of CPU taken by the hypervisor — this host machine is badly oversubscribed",
        "CPU 被宿主机抢走 %d%%" to "%d%% of CPU taken by the hypervisor",
        "CPU 被宿主机抢走 %d%%，偏高" to "%d%% of CPU taken by the hypervisor — on the high side",
        "交换分区用掉 %d%% —— 机器在颠簸，什么都会变慢" to "Swap %d%% used — the machine is thrashing, everything gets slow",
        "交换分区用掉 %d%%" to "Swap %d%% used",
        "开始用交换分区了（%d%%）" to "Starting to use swap (%d%%)",
        "负载是核数的 %.1f 倍，进程在排长队" to "Load is %.1f× the core count — processes are queueing",
        "负载是核数的 %.1f 倍" to "Load is %.1f× the core count",
        "内存用掉 %d%%，快没了" to "Memory %d%% used — nearly gone",
        "内存用掉 %d%%" to "Memory %d%% used",
        "根分区用掉 %d%%，快写不进去了" to "Root partition %d%% full — nearly out of space",
        "根分区用掉 %d%%" to "Root partition %d%% full",
        "Gradle 编译守护进程" to "Gradle build daemon",
        "Kotlin 编译守护进程" to "Kotlin compile daemon",
        "跑飞的 rg 全盘搜索" to "runaway rg full-disk search",
        "系统消息" to "system message",
        "这张图已经不在服务器上了（暂存区只留 3 天）" to "This image is no longer on the server (staging is kept for 3 days)",
        "浅色" to "Light",
        "深色" to "Dark",
        "这台手机不支持 16kHz 录音" to "This phone can't record at 16 kHz",
        "麦克风打不开（可能被别的应用占着）" to "Can't open the mic (another app may be using it)",
        "语音识别" to "Speech recognition",
        "这台设备不支持（只打包了 arm64）" to "Not supported on this device (arm64 only)",
        "已就绪 · 在手机上识别，离线也能用" to "Ready · runs on this phone, works offline",
        "下载中 %d%%" to "Downloading %d%%",
        "没下模型 · 现在用的是系统识别" to "No model · using the system recognizer",
        "⚠️ 只打包了 arm64 的原生库（模拟器和很老的机器用不了），这台机器会继续用系统识别。" to "⚠️ Only the arm64 native library is bundled (emulators and very old devices are out); this device keeps using the system recognizer.",
        "删掉模型（腾出约 %d MB）" to "Delete model (frees about %d MB)",
        "下载模型（%d MB）" to "Download model (%d MB)",
        "⚠️ 下载走流量，建议连 Wi-Fi。下好之后就一直在手机上，换服务器也不用重下。" to "⚠️ Uses mobile data — Wi-Fi recommended. Once downloaded it stays on the phone, even if you switch servers.",
        "识别**在这台手机上**做：不联网、不经过服务器、也不依赖 Google 服务。模型是开源的 SenseVoice，中英粤日都认、自带标点。" to "Recognition runs **on this phone**: no network, no server, no Google services. The model is the open-source SenseVoice — Chinese, English, Cantonese and Japanese, with punctuation.",
        "这台设备的 CPU 架构不支持（只打包了 arm64）" to "This CPU architecture isn't supported (arm64 only)",
        "语音模型还没下好" to "The speech model isn't downloaded yet",
        "语音模型装载失败：%s" to "Failed to load the speech model: %s",
        "识别失败：%s" to "Recognition failed: %s",
        "没给录音权限，用不了按住说话" to "Mic permission denied — hold-to-talk is off",
        "还没连上" to "Not connected yet",
        "录不了音：%s" to "Can't record: %s",
        "没识别出东西" to "Nothing recognized",
        "传不上去：%s" to "Upload failed: %s",
        "还没读到会话" to "No sessions loaded yet",
        "服务器上的会话没受影响，还在跑 —— 只是这会儿读不到。连上就回来。" to "Your sessions on the server are untouched and still running — this view just can't reach them. They'll be back on reconnect.",
        "已下好 · 点一下安装" to "downloaded · tap to install",
        "传着… %d/%d" to "uploading… %d/%d",
        "%d 个里有 %d 个没传上：%s" to "%d of %d failed to upload: %s",
        "这个文件读不出来" to "can't read this file",
        "旧数据" to "stale data",
        "刚刚的状态" to "as of just now",
        "%d 分钟前的状态" to "as of %d min ago",
        "%d 小时前的状态" to "as of %dh ago",
        "一直霸着 CPU 的进程" to "process hogging the CPU",
        "很久没动过的会话" to "sessions untouched for days",
        "%d 个 · %d MB · 最久 %d 天没动过" to "%d · %d MB · idle up to %d days",
        "正在取这个会话此刻的状态…" to "Getting this session's current state…",
        "这台手机上没有语音识别（多半是没装或关了 Google 服务）" to "No speech recognition on this phone (Google services are probably off or missing)",
        "叫不起语音识别：%s" to "Couldn't start speech recognition: %s",
        "正在载入对话…" to "Loading the conversation…",
        "载入失败：%s" to "Couldn't load: %s",
        "分组" to "Groups",
        "状态" to "Status",
        "没编组" to "Ungrouped",
        "「%s」组已打通，通知了 %d 个" to "\"%s\" is connected — told %d of them",
        "分组没存上：%s" to "Couldn't save the group: %s",
        "归到哪几个组" to "Which groups?",
        "同一个组里的 agent 能互相发消息（yxi-hub）。一个会话可以同时在好几个组里。" to "Agents in the same group can message each other (yxi-hub). A session can be in several groups at once.",
        "新建一个组…" to "New group…",
        "存下" to "Save",
        "没开成：%s" to "Didn't start: %s",
        "建不了这个目录 —— 没权限，或者上级路径不对" to "Can't create that directory — no permission, or the parent path is wrong",
        "tmux 起不来这个会话" to "tmux couldn't start that session",
        "tmux 没开在你指定的目录（跑到 %s 去了），已经撤销" to "tmux didn't start in the directory you gave (it landed in %s); undone",
        "别处" to "somewhere else",
        "没拿到结果 —— 连接可能断了" to "No result came back — the connection may have dropped",
        "说不上来" to "no idea",
        "检查更新" to "Check for updates",
        "贴进目标机的 ~/.ssh/authorized_keys 就能免密连。撤销 = 删掉那一行。" to "Paste it into the host's ~/.ssh/authorized_keys for passwordless login. To revoke, delete that line.",
        "查看 / 复制 / 换一把" to "View / copy / regenerate",
        "手机主动响" to "Ringing on your phone",
        "盯着的机器" to "Hosts watched",
        "%d 台" to "%d host(s)",
        "⚠️ 一台都没开 —— 前面两项放行了也不会响。" to "⚠️ None are on — the two items above won't make it ring by themselves. ",
        "去「主机」那一栏，点每台机器右边的铃铛把它打开。" to "Go to Hosts and tap the bell next to a machine.",
        "只通知置顶的会话" to "Only notify pinned sessions",
        "现在是**每个**会话都会响。会话多的时候通知栏会很吵。" to "Right now **every** session rings. With many sessions that gets noisy.",
        "⚠️ 一条都没置顶 —— 现在等于全部通知。" to "⚠️ Nothing is pinned — so this currently notifies everything. ",
        "去会话列表点卡片右上角的图钉，置顶几个你真正在等的。" to "Pin the ones you're actually waiting on, from the pin at the top right of a card.",
        "只有置顶的 %d 个会响，其余的静悄悄干活。" to "Only the %d pinned one(s) ring; the rest work quietly. ",
        "置顶在会话列表里点卡片右上角的图钉。" to "Pin from the top right of a session card.",
        "通知权限" to "Notification permission",
        "后台不受限制" to "Unrestricted background",
        "荣耀/华为还有一道单独的开关：设置 → 应用和服务 → 应用启动管理 → " to "Honor/Huawei has one more switch: Settings → Apps → App launch → ",
        "找到 Yxi → 关掉「自动管理」，然后三项（自启动/关联启动/后台活动）全打开。" to "find Yxi → turn off Manage automatically, then enable all three (auto-launch, secondary launch, background activity).",
        "缺任何一项，Claude 需要你时手机都不会响，而且不会有任何提示。" to "Miss any one of these and the phone stays silent when Claude needs you — with no warning.",
        "荣耀 / 华为 的后台管控尤其狠。" to "Honor and Huawei are especially aggressive about background apps.",
        "关于" to "About",
        "Yxi —— 手机上的 Claude Code 指挥台。\n" to "Yxi — a Claude Code console on your phone.\n",
        "全部走 SSH：不开新端口、不要证书、不经过任何第三方服务器。\n" to "Everything goes over SSH: no new ports, no certificates, no third-party servers.\n",
        "服务器上唯一需要装的是 yxi-hook（就为了让手机能主动响）。" to "The only thing to install on the server is yxi-hook — purely so the phone can ring.",
        "开发者模式" to "Developer mode",
        "口令" to "Passphrase",
        "口令不对" to "Wrong passphrase",
        "进" to "Enter",
        "开发者" to "Developer",
        "诊断会把整条连接路径一步步走一遍：解析地址 → 连 TCP → SSH 招呼 → 认证，" to "Diagnostics walks the whole path: resolve → TCP → SSH banner → auth, ",
        "再挨个试同一个 IP 上的几个端口。里面不含密码和私钥，可以直接贴出来。\n" to "then probes a few ports on the same IP. It contains no passwords or private keys — safe to paste.\n",
        "测的是 " to "Testing ",
        "（还没有主机）" to "(no hosts yet)",
        " —— 要换一台就去「会话」页顶部切换。" to " — switch hosts from the top of the Sessions page.",
        "测着…（约 30 秒）" to "Testing… (about 30s)",
        "跑一次诊断" to "Run diagnostics",
        "复制" to "Copy",
        "再连点三下版本号 = 退出开发者模式。" to "Triple-tap the version again to leave developer mode.",
        "已放行" to "Allowed",
        "去开启" to "Turn on",
        "第一次连这台主机" to "First time connecting to this host",
        "\n\n指纹\n" to "\n\nFingerprint\n",
        "\n\n请核对它跟服务器上 ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub " to "\n\nCheck it matches ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub ",
        "的输出一致。不一致就别连。" to "on the server. If it differs, don't connect.",
        "指纹对得上，连" to "Fingerprint matches — connect",
        "⚠️ 主机指纹变了，已拒绝连接。真是重装了就把这台主机删掉重加。" to "⚠️ The host fingerprint changed — connection refused. If it really was reinstalled, delete this host and add it again.",
        "地址解析不了：「%s」\n" to "Can't resolve the address: \"%s\"\n",
        "里面有个连不上的字符 %s —— 多半是中文输入法打的，删掉用英文键盘重打。" to "It contains an unusable character %s — probably typed with a CJK keyboard. Delete it and retype on an English one.",
        "这一栏要填 IP 或真实域名。手机上没有 ~/.ssh/config，" to "This field wants an IP or a real domain. There's no ~/.ssh/config on a phone, ",
        "SSH 别名（station 之类）在这儿用不了；也别带 http:// 或路径。" to "so SSH aliases (like \"station\") don't work here — and don't include http:// or a path.",
        "认证被拒：密码不对，或这台机器的 authorized_keys 里没有这把公钥。" to "Auth rejected: wrong password, or this key isn't in the host's authorized_keys.",
        "你取消了指纹确认，所以没连。" to "You cancelled the fingerprint check, so nothing connected.",
        "这台主机还没有可用的认证方式" to "This host has no usable auth method yet",
        "连接断了，正在重连…" to "Connection dropped — reconnecting…",
        "连接掉了，自动重连" to "Connection dropped, reconnecting",
        "归档的会话" to "Archived sessions",
        "没有归档的会话" to "Nothing archived",
        "没有会话" to "No sessions",
        "上滑取消归档 · 长按结束会话" to "Swipe up to unarchive · long-press to end",
        "上滑归档（不杀会话）· 长按结束会话" to "Swipe up to archive (session keeps running) · long-press to end",
        "会执行 tmux kill-session —— 那个会话里正在跑的东西**会被中断**，" to "This runs tmux kill-session — whatever that session is doing **gets interrupted**, ",
        "没保存的内容没了，取消不了。\n\n" to "unsaved work is lost, and it can't be undone.\n\n",
        "只是不想在列表里看见它的话，上滑归档就行，那个不动服务器。" to "If you just don't want it in the list, swipe up to archive — that touches nothing on the server.",
        "结束" to "End",
        "当前" to "Current",
        "已归档" to "Archived",
        "出错" to "Failed",
        "完成" to "Done",
        "进行中" to "Running",
        "覆盖已有文件" to "Overwrote existing file",
        "图片 " to "Image ",
        "后台跑" to "In background",
        "你拒绝了" to "You declined",
        "计划被否了" to "Plan rejected",
        "计划" to "Plan",
        "等你选（可多选）" to "Waiting on you (multi-select)",
        "等你选" to "Waiting on you",
        "提交" to "Submit",
        "下载并安装" to "Download and install",
        "以后" to "Later",
        "先在设置里允许本应用安装，然后再点一次" to "Allow installs from this app in settings, then tap again",
        "5 小时窗口" to "5-hour window",
        "对话" to "Chat",
        "没有指定会话" to "No session given",
        "这个会话里没跑过 Claude Code" to "Claude Code has never run in this session",
        "还没有置顶的会话" to "Nothing pinned yet",
        "全部会话…" to "All sessions…",
        "听到的是这句" to "Heard this",
        "确认后会原样打进终端并回车。识别错了就取消重说。" to "On confirm this is typed into the terminal verbatim and Enter is pressed. If it misheard, cancel and try again.",
        "发进终端" to "Send to terminal",
        "对话模式用不了" to "Chat mode unavailable",
        "。\n\n对话模式渲染的是 Claude Code 的转录文件；这个会话里没有，所以没东西可显示。终端和文件模式照常可用。" to ".\n\nChat mode renders Claude Code's transcript file; this session has none, so there's nothing to show. Terminal and Files still work.",
        "历史模式 · 上下滑动翻页 · 再点「历史」退出" to "History mode · swipe to page · tap History again to exit",
        "没有这个文件或目录" to "No such file or directory",
        "没有权限" to "Permission denied",
        "%d 项" to "%d items",
        "保存时会拆成：地址 %s" to "On save this splits into: host %s",
        "生成失败：%s: %s" to "Generation failed: %s: %s",
        "给 %s 装公钥" to "Install key on %s",
        "刷新失败：%s" to "Refresh failed: %s",
        "发送失败：%s" to "Send failed: %s",
        "%d 个会话 · 点读对话 · 长按发消息" to "%d sessions · tap to read · long-press to send",
        "发给 %s" to "Send to %s",
        "版本 %s" to "Version %s",
        "连不上 %s，没查成" to "Can't reach %s — check didn't run",
        "查的时候出错：%s" to "Error while checking: %s",
        "✓ 已是最新（服务器上就是 %s）" to "✓ Up to date (the server has %s)",
        "✗ 没查到：%s" to "✗ Not found: %s",
        "有新版本 %s · %s" to "New version %s · %s",
        "连不上 %s：%s\n检查 IP、端口，以及服务器是否开着。" to "Can't reach %s: %s\nCheck the IP, the port, and that the server is up.",
        "连不上：%s: %s" to "Can't connect: %s: %s",
        "归档 %d" to "Archived %d",
        "结束会话 %s？" to "End session %s?",
        "…还有 %d 行" to "…%d more lines",
        "有新版本 %s" to "New version %s",
        "下载失败：%s" to "Download failed: %s",
        "下载不完整（%d/%d），没装" to "Incomplete download (%d/%d) — not installed",
        "拉不起安装器：%s" to "Couldn't launch the installer: %s",
        "剩 %s" to "%s left",
        " · %dh 前" to " · %dh ago",
        "距重置 %s" to "%s to reset",
        " · %d/分" to " · %d/min",
        "终端起不来：%s" to "Terminal won't start: %s",
        "切不过去：%s" to "Couldn't switch: %s",
        "%d 个会话等你" to "%d session(s) waiting on you",
        "上下文 %s" to "context %s",
        "今日 %s · %s" to "today %s · %s",
        "没有闲着的会话可以借来查额度 —— 等它忙完再点" to "No idle session to borrow for the quota check — try again when one frees up",
        " 重置" to " reset",
        "额度" to "Quota",
        "问一下这台机器…" to "asking this host…",
        "5 小时额度" to "5-hour quota",
        "本周额度" to "This week",
        "点一下查" to "tap to check",
        "窗口已过" to "Window elapsed",
        "开选单…" to "opening…",
        "它正忙着，或者输入框里有没发完的字 —— 等一下再点" to "It's busy, or there's unsent text in its input box — try again in a moment",
        "同时设为默认（以后新开的会话都用它）" to "Also set as default (every new session will use it)",
        "不勾的话只换这个会话，别的会话和默认都不动。" to "Unchecked, this changes only this session — other sessions and the default stay put.",
        "界面风格" to "Look",
        "⚠️ 终端永远是深底 —— 彩色输出在浅底上读不了。所以浅色风格下切到终端会亮暗跳一下。" to "⚠️ The terminal stays dark — coloured output is unreadable on a light background. So on the light look, switching to the terminal jumps in brightness.",
        "已用 %d%% · 剩 %d%%" to "%d%% used · %d%% left",
        "5 小时" to "5-hour",
        "本周" to "Week",
        "%d 分钟前查的" to "checked %dm ago",
        "%d 小时前查的" to "checked %dh ago",
        "这个文件读不出来 —— 换一张试试" to "Can't read this file — try another",
        "开不了 SFTP 通道" to "Couldn't open an SFTP channel",
        "传失败：%s" to "Upload failed: %s",
        "盯着 %d 台" to "watching %d",
        "一台都没开" to "none on",
        "贴进目标机就能免密连" to "paste into a host for passwordless login",
        "Yxi —— 手机上的 Claude Code 指挥台" to "Yxi — a Claude Code console on your phone",
        "诊断连接、复制报告" to "diagnose the connection, copy the report",
        "版本" to "Version",
        "%s（versionCode %d）" to "%s (versionCode %d)",
        "没有空闲会话可借来查额度" to "No idle session to borrow for the quota check",
        "查不到额度 —— 这台机器上可能没有 claude" to "No quota — this host may not have claude",
        "%d 个会话 · 点一下进对话" to "%d sessions · tap to open",
        "长按卡片拖动可以改置顶次序" to "Long-press and drag to reorder pins",
        // 实验室
        "实验室" to "Lab",
        "动图 GIF" to "Animated GIF",
        "直接播 GIF/动图 —— 有些效果用现成动图比手写省事" to "Play a GIF directly — sometimes a ready-made clip beats hand-coding",
        "GIF" to "GIF",
        "这是一个 GIF 动图（原生播放，没引图片库）" to "This is a GIF (played natively, no image library)",
        "这台系统较旧，只显示 GIF 首帧" to "Older OS — showing the GIF's first frame only",
        // Yxxxxxi 加载候选
        "Yxxxxxi 加载候选" to "Yxxxxxi loader candidates",
        "抄 Dribbble 那个「字顶上滚东西」的 loading，做了 5 版 —— 左右滑着挑，勾选=审核通过" to "That Dribbble 'stuff rolling over the letters' loader, 5 takes — swipe to browse, tick = approved",
        "加载·候选" to "Loader·set",
        "顶部传送带" to "Top conveyor",
        "扫光填充" to "Wipe fill",
        "小球跳过" to "Hopping ball",
        "字母波浪" to "Letter wave",
        "底部点阵" to "Bottom dots",
        "← 滑 →" to "← swipe →",
        "✓ 已审核（第 %d 个）" to "✓ Approved (#%d)",
        "勾选 = 审核通过这个" to "Tick = approve this one",
        // Yxi 图标候选 + 参考动效
        "Yxi 图标候选" to "Yxi icon candidates",
        "4 个 logo 方向（❯提示符/对话气泡/Y字标/遥控）—— 左右滑着看，勾选=审核通过" to "4 logo directions (❯prompt / bubble / Y / orbit) — swipe to browse, tick = approved",
        "图标·审核" to "Icon·review",
        "参考动效收藏" to "Reference motion",
        "你发来的两个 Dribbble 动效，摆这儿随时看 —— 决定要不要复刻成真功能" to "The two Dribbble clips you sent, kept here — decide whether to rebuild them for real",
        "参考" to "Ref",
        "提交按钮 → 进度 → 成功/失败" to "Submit → progress → done/fail",
        "按钮变成进度条，跑完显示成功或「Oops!」。很适合我们的发送/连接动作。复刻价值高。" to "The button becomes a progress bar, ending in success or \"Oops!\". Great for our send/connect actions. Worth rebuilding.",
        "液态小球 → 打勾" to "Liquid blob → checkmark",
        "白球融来融去最后变对勾。当通用加载态好看。精确复刻较难，也可以直接用这个 GIF。" to "A white blob morphs and resolves into a check. Nice generic loader. Exact rebuild is hard — or just use the GIF as-is.",
        "✓ 想复刻这个" to "✓ Want this rebuilt",
        "勾选 = 想把这个复刻成真功能" to "Tick = want this rebuilt for real",
        "❯ 提示符" to "❯ Prompt",
        "命令行箭头 + 闪烁光标，最贴 Yxi 的身份" to "Command-line arrow + blinking cursor — closest to Yxi's identity",
        "对话气泡" to "Chat bubble",
        "气泡里嵌提示符，说「隔空跟 agent 对话」" to "A prompt inside a bubble — 'talk to your agent from afar'",
        "Y 字标" to "Y monogram",
        "干脆的字母 Y，最像传统 logo，百搭" to "A clean letter Y — most like a classic logo, versatile",
        "遥控" to "Remote",
        "核心 + 绕转的点，最抽象最有玩心" to "A core with an orbiting dot — most abstract, most playful",
        // 在线实验（服务器推）
        "在线实验（不用更新 App）" to "Live experiments (no app update)",
        "内容从服务器读 —— 我往 ~/.yxi/lab/ 放新设计，你点刷新就见，不用等发版" to "Content read from the server — I drop new designs in ~/.yxi/lab/, you refresh to see them, no release needed",
        "在线·推" to "Live·push",
        "在线实验 · 服务器推的" to "Live experiments · pushed from the server",
        "↻ 刷新" to "↻ Refresh",
        "还没有在线实验。\n\n开发者往服务器 ~/.yxi/lab/ 放东西（图片 / GIF / 网页 + manifest.json），你点上面「刷新」就出来 —— 不用更新 App。" to "No live experiments yet.\n\nThe developer drops files (image / GIF / web page + manifest.json) into ~/.yxi/lab/ on the server; tap Refresh above to see them — no app update.",
        "✓ 已审核" to "✓ Approved",
        // 实验室分栏
        "图像" to "Images",
        "矢量" to "Vectors",
        "动图" to "GIFs",
        "视频" to "Videos",
        "文字" to "Notes",
        "agent 产出的东西 · 按类型分栏 · 左滑置顶/删除" to "What your agents produce · grouped by type · swipe for pin/delete",
        "还是空的。\n\n让你的 agent 用 yxi-lab add <文件> 推东西进来（图像 / 网页 / 动图…），\n点上面「刷新」就按类型分栏出现 —— 不用更新 App。" to "Empty for now.\n\nHave your agents push things in with yxi-lab add <file> (images / web / GIFs…);\ntap Refresh above and they appear grouped by type — no app update.",
        "由 %s 生成" to "by %s",
        "%s 更新（北京）" to "updated %s (Beijing)",
        "%d 条" to "%d items",
        "%s（北京）" to "%s (Beijing)",
        // 变形提交按钮
        "失败了" to "Failed",
        "点重试" to "tap to retry",
        "已送达" to "Sent",
        "连接断了" to "Connection lost",
        "拉起安装器" to "Opening installer",
        "没连上" to "Not connected",
        "下载失败" to "Download failed",
        "刚刚" to "just now",
        "%d 分钟前" to "%dm ago",
        "%d 小时前" to "%dh ago",
        "%d 天前" to "%dd ago",
        "刚跑完 · %s" to "just finished · %s",
        "已发 /compact —— 压一下上下文" to "Sent /compact — compacting context",
        "▶ 正在做 · %s" to "▶ Doing · %s",
        "停" to "Stop",
        "编辑" to "Edit",
        "常用语（一行一句）" to "Quick replies (one per line)",
        "一行一句…" to "One per line…",
        "需要你决定" to "Needs your decision",
        "干完了" to "Done",
        "会话干完了" to "Session finished",
        "已等你 %d 分钟" to "Waiting %d min",
        "静音" to "Mute",
        "回一句" to "Reply",
        "回一句…" to "Reply…",
        "已静音 %s —— 之后不再提醒（会话卡长按可取消）" to "Muted %s — no more alerts (long-press its card to undo)",
        "🔕 静音" to "🔕 Muted",
        "🔔 取消静音" to "🔔 Unmute",
        "确认这次操作" to "Confirm this action",
        "看改动" to "View diff",
        "未提交的改动" to "Uncommitted changes",
        "%d 个会话在跑" to "%d sessions running",
        "Claude 正在干活" to "Claude is working",
        " · %d 在跑" to " · %d running",
        "%d 个等你" to "%d waiting",
        "点开去处理" to "Tap to handle",
        "%d 在跑" to "%d running",
        "盯着呢" to "Watching",
        "连不上，先在 App 里连一次这台主机" to "Can't connect — open the app and connect this host once first",
        "这台机器上没有会话" to "No sessions on this host",
        "看看这个" to "Take a look at this",
        "已送进 %s" to "Sent to %s",
        "没送出去" to "Not sent",
        "分享到哪个会话" to "Share to which session",
        "[文件] " to "[File] ",
        "新会话开在哪个目录" to "New session in which directory",
        "/opt/workspace/…" to "/opt/workspace/…",
        "开起来" to "Start",
        "下载" to "Download",
        "下载中…" to "Downloading…",
        "模式" to "Mode",
        "登录信息读不出来了，重新登一次" to "Your saved sign-in could not be read. Please sign in again.",
        "你的 agent 在服务器上跑，你在这儿把关" to "Your agents run on the server. You call the shots from here.",
        "登录 / 注册" to "Sign in / Sign up",
        "正在登录…" to "Signing in…",
        "登录只用来认人 —— 会员额度、兑换和工单跟账号走。\n你连哪台服务器、密钥放在哪，都只在这台手机上。" to "Signing in only identifies you — quota, redeem codes and tickets follow the account.\nWhich servers you connect to and where your keys live stay on this phone.",
        "这台手机上没有能打开网页的应用 —— 登录要跳浏览器，装一个再来" to "No app on this phone can open a web page. Signing in needs a browser — install one and try again.",
        "登录失效了，重新登一次" to "Your session expired. Please sign in again.",
        "← 上一题" to "← Prev",
        "下一题 →" to "Next →",
        "确认提交" to "Confirm",
        "提交答案" to "Submit",
        "多选：点选项是勾/取消，选完再点提交" to "Multi-select: tap to check/uncheck, then Submit",
        "连不上下载页：%s" to "Can't reach the download page: %s",
        "下载页没返回内容" to "The download page returned nothing",
        "下载页上没有安装包" to "No APK on the download page",
        "工单中心" to "Feedback",
        "哪里不好用，随手记一条" to "Something not working? Jot it down",
        "写下来存在这台服务器上（~/.yxi/tickets.jsonl），开发那边直接查阅。会自动带上版本号和机型。" to "Saved on this server (~/.yxi/tickets.jsonl) for the devs to read. Version and device are attached automatically.",
        "比如：点了发送切出去，消息没发出去" to "e.g. tapped send, switched away, message never arrived",
        "提一条" to "Submit",
        "记下了" to "Noted",
        "先写点什么" to "Write something first",
        "已提 %d 条" to "%d submitted",
        "没发出去，话给你留在输入框了" to "Not sent — your message is back in the box",
        "最大思考" to "Max thinking",
        "高强度" to "High effort",
        "中等" to "Medium",
        "计划模式" to "Plan mode",
        "已发 %s" to "Sent %s",
        "切模式" to "Switch mode",
        "点一下就发进会话；能叠加的连着点，比如先 1M 再 最大思考。" to "Tap to send into the session; stack by tapping several — e.g. 1M then max-thinking.",
        "编辑模式（一行一个：名字|命令）" to "Edit modes (one per line: name|command)",
        "例：最大思考|/effort max —— 命令按你的 Claude Code 实际能用的填" to "e.g. Max thinking|/effort max — use whatever command actually works in your Claude Code",
        "配置" to "Config",
        "这台机器上的 agent 配置" to "Agent config on this machine",
        "这台机器上没找到配置" to "No config found on this machine",
        "装了 Claude Code（~/.claude）或 Codex（~/.codex）才有" to "Needs Claude Code (~/.claude) or Codex (~/.codex)",
        "读不到" to "Can't read it",
        "保存中…" to "Saving…",
        "已保存（旧版已备份）" to "Saved (old version backed up)",
        "⚠️ 这是结构化配置，改坏语法会让工具起不来；保存前会自动备份、json 会先校验。密钥此刻明文可见，当心别人看屏。" to "⚠️ Structured config — a syntax error can break the tool; it's backed up before saving and JSON is validated first. Secrets are shown in the clear here — mind who's looking.",
        "保存原图" to "Save image",
        "保存 GIF" to "Save GIF",
        "保存视频" to "Save video",
        "下载到本地" to "Download",
        "已保存" to "Saved",
        "已存到相册" to "Saved to gallery",
        "已存到下载目录" to "Saved to Downloads",
        "保存到本地需要 Android 10 及以上" to "Saving needs Android 10 or newer",
        "建不了文件（存储可能满了）" to "Can't create the file (storage may be full)",
        "写不进去" to "Couldn't write it",
        "装好了，已切密钥" to "Installed · switched to key",
        "装好了（%s 行公钥）" to "Installed (%s key lines)",
        "UI 实验台 · 点一张卡看效果 · 好的再并进正式界面" to "UI playground · tap a card to see it · good ones graduate into the app",
        "加载 UI 合集" to "Loading UI set",
        "圆环 / 三点跳动 / 骨架屏微光 / 进度条 —— 挑一个当加载态" to "Ring / bouncing dots / skeleton shimmer / bar — pick a loading state",
        "加载" to "Loading",
        "弹簧动效" to "Spring motion",
        "点一下看 spring / 展开收起 / 淡入淡出" to "Tap to see spring / expand-collapse / cross-fade",
        "动效" to "Motion",
        "网页效果" to "Web effects",
        "WebView 开着 JS 跑 canvas 动画 —— 文件预览里 JS 是关的，这儿是可信游乐场" to "WebView with JS on running a canvas animation — JS is off in the file viewer; this is a trusted playground",
        "网页" to "Web",
        "新页面原型" to "New page mockup",
        "一个成品级的资料页样子 —— 演示「新的一页 UI」怎么长" to "A polished profile page — showing what a new page UI looks like",
        "原型" to "Mockup",
        "圆环" to "Ring",
        "三点跳动" to "Bouncing dots",
        "骨架屏微光" to "Skeleton shimmer",
        "进度条" to "Progress bar",
        "弹簧缩放（点方块）" to "Spring scale (tap the box)",
        "点我" to "Tap me",
        "展开收起" to "Expand / collapse",
        "收起 ▲" to "Collapse ▲",
        "展开 ▼" to "Expand ▼",
        "藏起来的内容 —— 用 AnimatedVisibility，进出都有过渡。" to "Hidden content — via AnimatedVisibility, animated in and out.",
        "翻转淡入" to "Cross-fade",
        "正面" to "Front",
        "背面" to "Back",
        "示例用户" to "Sample User",
        "这是实验室里的一张页面原型" to "A page mockup in the Lab",
        "实验" to "Experiments",
        "账号设置" to "Account",
        "通知偏好" to "Notifications",
        "外观风格" to "Appearance",
        "已经等了 %s" to "waiting %s",
        "%d 分钟" to "%dm",
        "%d 小时" to "%dh",
        "%d 天" to "%dd",
        "%s 取的" to "read %s",
        "或者直接填：/opt/workspace/…" to "or type a path: /opt/workspace/…",
        "找目录中…" to "Looking for directories…",
        "查不到：%s" to "Can't check: %s",
        "查询超时：claude -p '/usage' 要连 API，30 秒没回来" to "Timed out: `claude -p '/usage'` calls the API and didn't answer in 30s",
        "认不出 /usage 的输出 —— 多半是 Claude Code 换排版了" to "Can't read the /usage output — Claude Code probably changed its layout",
        "还没连上，或者那台机器上没有工作区目录 —— 下面直接填路径也行。" to "Not connected, or no workspace dirs on that machine — type a path below.",
        "这些工作区目录都已经开着会话了 —— 下面直接填个新路径。" to "Every workspace dir already has a session — type a new path below.",
        "这台机器上没装 claude —— 额度是问它要的" to "No `claude` on this machine — that's where the quota comes from",
        "连接出错" to "Connection error",
        "选一个还没开会话的目录，会在那儿开一个会话并把 claude 跑起来。" to "Pick a directory without a session — Yxi opens one there and starts claude.",
        "连接" to "Connect",
        "Agent 配置" to "Agent config",
        "认证一次，这台机器上的 Claude Code 就能直接调用它。全程在手机上完成。" to "Sign in once and Claude Code on this machine can call the service directly. Everything happens on your phone.",
        "这台机器上没有 claude 命令，MCP 那几项接不了；GitHub 仍然可以。" to "No `claude` command on this machine, so the MCP items can't be connected; GitHub still works.",
        "+ 自定义 MCP 地址…" to "+ Custom MCP URL…",
        "打不开浏览器：%s" to "Can't open the browser: %s",
        "断开 %s？" to "Disconnect %s?",
        "会退出 gh 的登录，git 推拉和 GitHub MCP 一起失效。" to "This signs gh out; git push/pull and the GitHub MCP stop working.",
        "会从 Claude Code 的配置里删掉这个 MCP。" to "This removes the MCP server from Claude Code's config.",
        "断开" to "Disconnect",
        "已连接" to "Connected",
        "要登录" to "Sign-in needed",
        "连不上" to "Unreachable",
        "加上" to "Add",
        "登录" to "Sign in",
        "准备中…" to "Preparing…",
        "在服务器上起 gh 登录…" to "Starting gh login on the server…",
        "gh 没给出一次性码（这台机器装了 gh 吗？）" to "gh didn't print a one-time code (is gh installed on this machine?)",
        "GitHub 接上了：git 推拉和 GitHub MCP 都能用了" to "GitHub connected: git push/pull and the GitHub MCP both work now",
        "加进 Claude Code…" to "Adding to Claude Code…",
        "加上了，不用登录，直接就能用" to "Added. No sign-in needed, it just works.",
        "等授权地址…" to "Waiting for the authorization link…",
        "没拿到授权地址" to "Didn't get an authorization link",
        "%s 接上了" to "%s connected",
        "等了 10 分钟没结果，服务器那头的流程已经停了" to "No result after 10 minutes; the server-side flow has been stopped",
        "连接 %s" to "Connect %s",
        "GitHub 页面会要一个一次性码。点下面按钮：码已复制、页面已打开，粘进去按确认就行。" to "GitHub will ask for a one-time code. Tap the button: the code is copied and the page opens; paste it and confirm.",
        "等 GitHub 那边确认…（确认完这里会自己变）" to "Waiting for GitHub to confirm… (this updates by itself)",
        "码 15 分钟内有效" to "The code is valid for 15 minutes",
        "在浏览器里登录并同意。同意之后页面会自己跳回来，这里会显示接上了。" to "Sign in and approve in the browser. After approving, the page returns on its own and this shows connected.",
        "在浏览器里登录并同意。同意之后浏览器会停在一个打不开的 localhost 页面 —— 把地址栏那串地址复制过来粘到下面。" to "Sign in and approve in the browser. Afterwards the browser stops on a localhost page that won't load — copy the address bar and paste it below.",
        "等浏览器那边授权…" to "Waiting for the browser authorization…",
        "跳不回来？把 localhost 开头的地址粘这儿" to "Didn't return? Paste the localhost… address here",
        "交上去" to "Submit",
        "复制码并打开 GitHub" to "Copy code & open GitHub",
        "去浏览器授权" to "Authorize in browser",
        "好" to "OK",
        "先关掉" to "Close for now",
        "自定义 MCP" to "Custom MCP",
        "名字（字母数字）" to "Name (letters/digits)",
        "地址（https://…/mcp 或 /sse）" to "URL (https://…/mcp or /sse)",
        "加进去之后会走一遍登录；不需要登录的服务登录那步会自己过。" to "After adding, a sign-in runs; for services that need none, that step passes by itself.",
        "git 推拉、仓库 / PR / Issue" to "git push/pull, repos / PRs / issues",
        "读写页面和数据库" to "Read & write pages and databases",
        "工单" to "Issues",
        "错误监控" to "Error monitoring",
        "Atlassian" to "Atlassian",
        "任务" to "Tasks",
        "支付" to "Payments",
        "几千个应用的自动化" to "Automation across thousands of apps",
        "部署" to "Deployments",
        "域名 / Workers" to "Domains / Workers",
        "数据库" to "Databases",
        "设计稿" to "Design files",
        "设计" to "Design",
        "客服" to "Support inbox",
        "项目" to "Projects",
        "模型 / 数据集" to "Models / datasets",
        "各种库的最新文档" to "Up-to-date docs for libraries",
        "读任何 GitHub 仓库的文档" to "Docs for any GitHub repo",
        "只有 claude.ai 订阅登录才有（claude.ai 连接器），用 API key 的没有" to "Only with a claude.ai subscription login (claude.ai connectors); not available with an API key",
        "浏览器插件只配同一台电脑上的 Claude Code，远程服务器用不了" to "The browser extension only pairs with Claude Code on the same computer; not usable from a remote server",
        "收起" to "Collapse",
        "弹窗提醒（横幅）" to "Pop-up alerts (banner)",
        "会弹" to "Pops up",
        "这条频道被降级了，通知只会进列表不弹出来。点「去开启」，把重要程度调回「高」并打开横幅。" to "This channel was demoted, so alerts only land in the list. Tap Enable, set importance back to High and turn banners on.",
        "发一条试试" to "Send a test",
        "弹一条" to "Test it",
        "正常情况下它会像微信来消息一样弹在屏幕顶上、震两下；锁屏时会点亮屏幕。没弹出来就是上面哪一项没放行。" to "Normally it pops up at the top like a chat message and buzzes twice; on the lock screen it wakes the display. If nothing pops up, one of the items above is still blocked.",
        "演示机 需要你（这是试的）" to "Demo host needs you (test)",
        "Claude 停下来等你的时候，就是这样弹出来。" to "This is how it looks when Claude stops and waits for you.",
        "抓回来的不完整（连接可能半断了）" to "Incomplete snapshot (the connection may be half-dead)",
        "点一下关闭" to "Tap to close",
        "开屏动效 · 待你审" to "Launch animation · for your review",
        "现在用的：%s" to "In use: %s",
        "%d 个方案，一个都还没定 —— 冷启动暂时不播" to "%d options, none chosen yet — nothing plays at launch for now",
        "播放" to "Play",
        "用着" to "In use",
        "就用这个" to "Use this",
        "选中的那个会在冷启动时播一遍；再点一次「用着」就取消。" to "The chosen one plays once at cold start; tap In use again to cancel.",
        "笔触书写" to "Brush stroke",
        "像毛笔从左往右把 Yunxi 写出来，前沿带一点渗墨" to "A brush writes Yunxi left to right, with ink bleeding at the edge",
        "光晕绽放" to "Glow bloom",
        "对话页那四团粉彩光从中心绽放，Y 先弹出来，再化成整个字" to "The chat page's four pastel glows bloom from the centre; the Y pops first, then becomes the full word",
        "墨迹落定" to "Ink settles",
        "一笔墨从空中落到纸上、渗开、定住，再扫过一道光" to "A stroke of ink lands on paper, bleeds, settles, then a light sweeps across",
        "粒子聚合" to "Particles converge",
        "几百个小点从四面八方飞进来拼成 Yunxi，再化成真正的字" to "Hundreds of dots fly in from all sides to form Yunxi, then become the real word",
        "Y 落下，字展开" to "Y drops, word unfolds",
        "Y 从上面落下弹两下、起一圈涟漪，然后整个字向右展开" to "The Y drops in and bounces twice with a ripple, then the word unfolds to the right",
        "%s 这台的 · " to "%s · ",
        "✓ 已采纳" to "✓ Adopted",
        "采纳" to "Adopt",
        "全屏" to "Full screen",
        "读不到这条内容（连接断了？）—— 点上面的刷新" to "Couldn't load this item (connection dropped?) — tap refresh above",
        "页面报错：%s" to "Page error: %s",
        "等了 %s" to "waited %s",
        "目录太大，只列了前 %d 项" to "Directory too large; showing the first %d entries",
        "图片 %d MB，太大没加载" to "Image is %d MB, too large to load",
        "图片读不到：%s" to "Couldn't load image: %s",
        "加载中…" to "Loading…",
        "这台机器上没有 tmux —— 登录和会话都靠它。点上面「安装」一键装机，会一起装上。" to "This machine has no tmux — logins and sessions depend on it. Tap “Install” above; the one-tap setup installs it too.",
        "会退出这台机器上 %s 的登录，会话里再用得重新登。" to "This signs %s out on this machine; sessions will need a fresh login.",
        "没装" to "Not installed",
        "已登录" to "Signed in",
        "⚠️ 其中 %s 要重开会话（或用 /model、/effort）才变。" to "⚠️ %s only change after you restart the session (or use /model, /effort).",
        "隐藏 AI 署名" to "Hide AI co-author line",
        "Teammates 模式" to "Teammates mode",
        "启用 Tool Search" to "Enable Tool Search",
        "最大强度思考" to "Max thinking effort",
        "禁用自动升级" to "Disable auto-update",
        "预设" to "Preset",
        "选一个中转 / 官方预设 ▾" to "Pick a relay / official preset ▾",
        "备注（可空）" to "Note (optional)",
        "▾ 高级 JSON（整段 settings 片段）" to "▾ Advanced JSON (the whole settings fragment)",
        "▸ 高级 JSON（整段 settings 片段）" to "▸ Advanced JSON (the whole settings fragment)",
        "保存时以这段为准：env 里的三个核心键会回填到上面三个框；其余键（模型映射、model、effortLevel…）跟着线路一起切。" to "On save this fragment wins: the three core env keys are copied back into the fields above; every other key (model mapping, model, effortLevel…) switches together with the line.",
        "JSON 格式不对：%s" to "Invalid JSON: %s",
        "env 必须是对象" to "env must be an object",
        "这些键不允许由线路写入（安全）：%s" to "These keys can't be written by a line (security): %s",
        "余额兑换码兑入 · 商城买会员码 · 到期自动续费" to "Top up with balance codes · buy membership codes in the shop · auto-renew on expiry",
        "商城" to "Shop",
        "余额 %s · 买到的是一张不记名兑换码，自己兑或送人都行；同档叠加、时间往后累加。" to "Balance %s · you get a bearer redeem code — use it yourself or give it away; same-tier codes stack, time adds on.",
        "取不到商品 —— 网络不通，或者登录过期了。" to "Can’t load the shop — no network, or your login expired.",
        "%d 天 · %s 的兑换码" to "%d days · %s redeem code",
        "还差 %s" to "%s short",
        "买 %s？" to "Buy %s?",
        "从余额扣 %s，得到一张 %d 天的 %s 兑换码。" to "Deducts %s from your balance for a %d-day %s redeem code.",
        "余额不够：还差 %s（余额 %s）" to "Not enough balance: %s short (balance %s)",
        "没买成：%s" to "Purchase failed: %s",
        "买着…" to "Buying…",
        "确认" to "Confirm",
        "这单之前已经买过了" to "This order already went through",
        "买好了" to "Bought",
        "刚才那次其实已经成功，没有重复扣钱。这就是那张码：" to "Your earlier attempt actually succeeded — nothing was charged twice. Here is the code:",
        "%d 天 %s · 已扣 %s · 余额 %s\n码也发到了你的邮件里。去会员中心兑，同档会叠加。" to "%d days %s · charged %s · balance %s\nThe code was also mailed to you. Redeem it in Membership; same-tier codes stack.",
        "去兑换" to "Redeem",
        "先放着" to "Later",
        "余额" to "Balance",
        "有一笔兑换被撤销了 · 下次兑余额券会先抵这笔" to "A redemption was reversed · the next balance code covers it first",
        "余额靠「余额兑换码」兑入（会员中心 → 兑换码），可以去商城买会员码，或者到期自动续费。" to "Balance comes from balance redeem codes (Membership → Redeem code). Spend it in the shop on membership codes, or let it auto-renew on expiry.",
        "到期自动续费" to "Auto-renew on expiry",
        "免费版没有东西可续 —— 兑一张会员码之后这里就能开" to "Nothing to renew on Free — redeem a membership code and this switch unlocks",
        "到期那天从余额扣 %s 续一期 %s；余额不够就正常到期，不会扣成负数" to "On expiry, %s is deducted to renew one %s period; if the balance is short it simply expires — never goes negative",
        "没改成：%s" to "Couldn’t change it: %s",
        "用余额买 Pro / Ultra 的兑换码，同档叠加、时间往后累加" to "Buy Pro / Ultra redeem codes with your balance; same tier stacks, time adds on",
        "订单记录" to "Orders",
        "还没买过东西。" to "Nothing bought yet.",
        "码在会员中心 → 兑换码里输，同档会叠加。" to "Enter codes under Membership → Redeem code; same tier stacks.",
        "临时会话" to "Temporary session",
        "不保存" to "Not saved",
        "在服务器 /tmp 里开一个新对话。不保存：重启 Yxi 就没了。" to "Opens a fresh conversation under /tmp on the server. Not saved: gone when Yxi restarts.",
        "模型" to "Model",
        "也可以直接填模型名" to "Or type a model name",
        "模型名只能是字母数字和 -[]._" to "Model name may only contain letters, digits and -[]._",
        "开着…" to "Opening…",
        "开始" to "Start",
        "走 Codex 自己的登录" to "Codex’s own login",
        "Codex 已改到「%s」· %s\n⚠️ 要重开 Codex 会话才生效 —— 它的配置是启动时读的，不像 Claude Code 能热切。" to "Codex switched to “%s” · %s\n⚠️ Takes effect only after you restart the Codex session — it reads its config at startup, unlike Claude Code which switches live.",
        "排队中：%s这一轮跑完就换到「%s」（%s）" to "Queued: %sswitches to “%s” once this turn finishes (%s)",
        "取不到线路清单 —— 没连上那台机器，或者服务器上的 lines.json 被改坏了。" to "Can’t load the line list — not connected to that machine, or lines.json on the server is corrupted.",
        "Codex 换线要重开那个会话才生效 —— 它的配置是进程启动时读的，不像 Claude Code 能热切。" to "Switching lines for Codex takes effect only after that session restarts — it reads its config at process start, unlike Claude Code which switches live.",
        "默认（走 Codex 自己的登录）" to "Default (Codex’s own login)",
        "端点 base_url" to "Endpoint base_url",
        "密钥（存服务器上 600 的文件里）" to "Key (stored on the server in a 600 file)",
        "Codex 走 config.toml 的 model_provider；钥匙不写进 config.toml，另存一个只有你能读的文件。" to "Codex uses model_provider in config.toml; the key is not written into config.toml but kept in a separate file only you can read.",
        "Claude Code" to "Claude Code",
        "有 %d 封信里的东西还没领" to "%d mails have unclaimed items",
        "长按复制" to "Long-press to copy",
        "复制好了" to "Copied",
        "这串码自己去「兑换」里输" to "Enter this code yourself under Redeem",
        "已领取" to "Claimed",
        "没领到 —— 网络不通或登录过期了，东西还在信里。" to "Couldn’t claim — no network, or your login expired. The items are still in the mail.",
        "这封信之前已经领过了，没有重复发" to "This mail was already claimed; nothing was granted twice",
        "领好了" to "Claimed",
        "领取中…" to "Claiming…",
        "领取" to "Claim",
        "切换中…" to "Switching…",
        "已切到 %s · 也成了账号默认" to "Switched to %s · now the account default too",
        "点一下就切，顺便写成账号默认（以后新会话也用它）。" to "One tap switches it and makes it the account default (new sessions use it too).",
        "只换这个会话，不改默认（慢，要开选单）→" to "Only this session, keep the default (slow — opens the menu) →",
        "思考强度" to "Effort",
        "低" to "Low",
        "会一并写成账号默认。" to "Also becomes the account default.",
        "整台机器" to "Whole machine",
        "只给「%s」" to "Just \u201C%s\u201D",
        "%s已换到「%s」· %s\n下一次请求就走新线路；那一次会重读整段对话，慢一点、贵一点，是正常的。" to "%sSwitched to \u201C%s\u201D \u00b7 %s\nThe next request uses the new line; that one re-reads the whole conversation, so it is slower and costs more. That is normal.",
        "不再单独设置，跟随整机" to "Stop overriding \u2014 follow the machine",
        "要重开这个会话才生效" to "Takes effect only after you restart this session",
        "没撤掉：%s" to "Couldn\u2019t remove it: %s",
        "已撤掉「%s」的单独设置。\n⚠️ 这一步要重开那个会话才真正生效 —— 「跟随整机」只能靠把设置删掉来表达，而删掉不会热生效，旧值还留在那个进程里。" to "Removed the override for \u201C%s\u201D.\n\u26a0\ufe0f This one only takes effect after you restart that session \u2014 \u201Cfollow the machine\u201D can only be expressed by deleting the setting, and a deletion is not picked up live: the old value is still in that process.",
        "有一笔兑换被撤销了 · 下次充值先抵这笔" to "A redemption was reversed · your next top-up covers it first",
        "当前余额 %s" to "Balance now %s",
        "筛选" to "Filter",
        "派给哪个会话 · 默认发回给生成它的 %s" to "Send to which session · defaults back to %s, which made it",
        "即将推出（现在抽不到）" to "Coming soon (not obtainable yet)",
        "角色" to "Characters",
        "装扮" to "Skins",
        "已拥有 %d / %d" to "Owned %d / %d",
        "终端配色" to "Terminal colours",
        "气泡配色" to "Bubble colours",
        "快捷语包" to "Phrase packs",
        "没跟服务端对上 —— 下面按上次同步的结果显示，可能不是最新的。" to "Couldn't reach the server — showing the last synced state, which may be out of date.",
        "未拥有" to "Not owned",
        "使用中" to "In use",
        "已生效" to "Applied",
        "快捷语包·协作" to "Phrase pack · Teamwork",
        "快捷语包·排查" to "Phrase pack · Debugging",
        // 装扮名（走 t(zh) 变量，dev/i18n-check.sh 扫不出来 —— 跟 Skin.Style / SessionState.label 同一个盲区）
        "默认" to "Default",
        "终端·琥珀" to "Terminal · Amber",
        "终端·青" to "Terminal · Teal",
        "终端·纸白" to "Terminal · Paper",
        "终端·夜航" to "Terminal · Night",
        "气泡·暖" to "Bubble · Warm",
        "气泡·冷" to "Bubble · Cool",
        "气泡·墨" to "Bubble · Ink",
        "气泡·晨" to "Bubble · Dawn",
        "祈愿记录" to "Wish history",
        "十连" to "10-pull",
        "单抽" to "Single",
        "NEW" to "NEW",
        "重复 · 折曦光 ×%d" to "Duplicate · converted to %d Rays",
        "会员 %d 天" to "%d days of membership",
        "取不到 —— 网络不通，或者登录过期了。记录在服务端，没丢。" to "Couldn't load — no network, or your sign-in expired. The history lives on the server; nothing is lost.",
        "还没有记录。去祈愿页抽一次，抽到什么都会记在这里。" to "No history yet. Make a wish and everything you get will be listed here.",
        "安装" to "Install",
        "退出" to "Sign out",
        "在服务器上起 Claude Code 登录…" to "Starting Claude Code login on the server…",
        "没拿到登录地址（这台机器装了 claude 吗？）" to "No login URL came back (is claude installed on this machine?)",
        "Claude Code 登录好了，会话里直接能用" to "Claude Code is signed in — sessions can use it right away",
        "在服务器上起 Codex 登录…" to "Starting Codex login on the server…",
        "Codex 没给出一次性码（这台机器装了 codex 吗？）" to "Codex didn't show a one-time code (is codex installed on this machine?)",
        "Codex 登录好了，会话里直接能用" to "Codex is signed in — sessions can use it right away",
        "%s 页面会要一个一次性码。点下面按钮：码已复制、页面已打开，粘进去按确认就行。" to "The %s page asks for a one-time code. Tap the button below: the code is copied and the page opens — paste it and confirm.",
        "等 %s 那边确认…（确认完这里会自己变）" to "Waiting for %s to confirm… (this updates by itself)",
        "在浏览器里登录并同意。之后页面会给你一串码 —— 复制过来粘到下面。" to "Sign in and approve in the browser. The page then shows a code — copy it and paste it below.",
        "把页面给的那串码粘这儿" to "Paste the code from the page here",
        "复制码并打开 %s" to "Copy code and open %s",
        "Codex 会话 —— 状态和对话在终端里看" to "Codex session — state and conversation live in the terminal",
        "选一个还没开会话的目录，会在那儿开一个会话并把 %s 跑起来。" to "Pick a directory without a session; one will be opened there with %s running.",
        "这台机器上还没有 Claude Code / Codex" to "No Claude Code or Codex on this machine yet",
        "连 tmux 也没有 —— 一键装机会把 tmux、Claude Code、Codex 和 Yxi 的钩子一起装上，不需要 Node.js。" to "Not even tmux — one-tap setup installs tmux, Claude Code, Codex and Yxi's hooks. No Node.js needed.",
        "一键装机会把 Claude Code、Codex 和 Yxi 的钩子装上，不需要 Node.js。装完在「配置 → 连接」里登录。" to "One-tap setup installs Claude Code, Codex and Yxi's hooks. No Node.js needed. Then sign in under Config → Connect.",
        "一键装机" to "One-tap setup",
        "等了 25 分钟还没结束 —— 用终端看看 ~/.yxi/setup.log" to "Still not finished after 25 minutes — check ~/.yxi/setup.log in the terminal",
        "在装：tmux · Claude Code · Codex · Yxi 钩子（几分钟）" to "Installing: tmux · Claude Code · Codex · Yxi hooks (a few minutes)",
        "装好了。下一步：「配置 → 连接」里登录 Claude Code / Codex。" to "Done. Next: sign in to Claude Code / Codex under Config → Connect.",
        "有几项没装成 —— 看下面 ⚠ 的行；再点一次只补没装的。" to "Some items failed — see the ⚠ lines below; tapping again only installs what's missing.",
        "先关掉（后台继续装）" to "Close for now (setup continues in the background)",
        "Codex 会话没有对话视图 —— 用终端" to "Codex sessions have no chat view — use the terminal",
        "码不对 —— 回页面把整串码重新复制一遍" to "Wrong code — go back to the page and copy the whole code again",
        "探测并装机" to "Probe and install",
        "没看到 Claude Code / Codex 在跑" to "No Claude Code / Codex running",
        "探测 →" to "Probe →",
        "探测 Claude Code / Codex" to "Probe Claude Code / Codex",
        "探不到（连接可能半断了）—— 再试一次" to "Probe failed (the connection may have dropped) — try again",
        "在探…" to "Probing…",
        "系统" to "System",
        "非 root" to "not root",
        "已登录 %s" to "signed in as %s",
        "没登录" to "not signed in",
        "没有（不需要）" to "none (not needed)",
        "一个都没装。选好要装什么，点「一键装机」—— tmux 和 Yxi 的钩子会一起装，不需要 Node.js。" to "Nothing installed. Pick what to install and tap “One-tap setup” — tmux and Yxi's hooks come along; no Node.js needed.",
        "装了但没登录 —— 去「配置 → 连接」登录。下面再装只会补缺的。" to "Installed but not signed in — sign in under Config → Connect. Installing again only fills in what's missing.",
        "都在。下面再装只会补缺的、刷一遍 Yxi 的钩子。" to "All present. Installing again only fills in what's missing and refreshes Yxi's hooks.",
        "都装" to "Both",
        "再探一次" to "Probe again",
        "关掉" to "Close",
        "Yxi 钩子" to "Yxi hooks",
        "在装：%s（几分钟）" to "Installing: %s (a few minutes)",
        "%s · 没装，点我去装" to "%s · not installed, tap to install",
        "探测 / 装机" to "Probe / install",
        "%s · 失败，点我重试" to "%s · failed, tap to retry",
        "语音识别就绪：按住麦克风说话，松开就识别（点一下不行）" to "Voice input ready: hold the mic to talk and release to transcribe (a tap does nothing)",
        "要按住说话，松开才识别" to "Hold to talk, release to transcribe",
        "目录" to "Folder",
        "全部目录" to "All folders",
        "清掉了 %d 条草稿，重进对话就是空的" to "Cleared %d drafts; the composer will be empty when you reopen a chat",
        "清空所有输入框草稿（输入框卡住时用）" to "Clear all composer drafts (use when the input box is stuck)",
        "组规 ✓" to "Rules ✓",
        "组规" to "Rules",
        "「%s」的组规" to "Rules for “%s”",
        "写给这个组每个 agent 的话。每个会话开始时（含接回、/compact 之后）自动注入，不用建文件、不用改 CLAUDE.md。" to "A note for every agent in this group. Injected automatically whenever a session starts (including resume and after /compact) — no files, no CLAUDE.md edits.",
        "例：遇到值得记录的架构信息 / 密钥位置，按分组归档到 E:\\资料，方便各项目取用。" to "e.g. When you come across architecture facts or key locations worth keeping, file them by group under E:\\资料 for other projects to use.",
        "空着保存 = 删掉这条组规。agent 里随时能用 yxi-hub rules 看自己组的组规。" to "Save empty to remove the rule. Agents can run yxi-hub rules to read their groups' rules any time.",
        "存并发给在跑的 %d 个" to "Save and tell the %d running now",
        "「%s」组规已存，并发给了 %d 个在跑的会话" to "Rules for “%s” saved and sent to %d running sessions",
        "「%s」组规已存，本组会话下次开始时生效" to "Rules for “%s” saved; they apply when this group's sessions next start",
        "组规没存上：%s" to "Couldn't save the rules: %s",
        "v%s · 手机上的指挥台" to "v%s · your servers, in your pocket",
        "这里放什么，等你定" to "What goes here is up to you",
        "搜索" to "Search",
        "搜会话名 / 目录 / 状态词" to "Search by session, folder or status",
        "%d 个匹配「%s」 · 共 %d 个" to "%d match “%s” · %d in total",
        "%d 个在 %s 下 · 共 %d 个" to "%d under %s · %d in total",
        "%d 个会话" to "%d sessions",
        "（共 %d 个）" to " (%d in total)",
        "查明并画出来" to "Discover and diagram",
        "把结构画成图" to "Draw what I describe",
        "已派给 %s —— 画好会出现在这里（每 20 秒自动刷一次）" to "Sent to %s — it will appear here when done (auto-refresh every 20 s)",
        "更新" to "Update",
        "更新《%s》" to "Update “%s”",
        "不填就默认：把当前项目查明并画成可验证架构图（confirmed / inferred / unknown / conflict + 证据）" to "Leave empty for the default: reverse-engineer this project into a verifiable architecture diagram (confirmed / inferred / unknown / conflict + evidence)",
        "不填就默认：把这个项目的模块关系画成依赖图。填了就按你说的画（流程 / 时序 / ER / C4 / Gantt…）" to "Leave empty for the default: a dependency diagram of this project's modules. Or describe what to draw (flow / sequence / ER / C4 / Gantt…)",
        "不填就默认：按项目现状重画这一张、原位替换。填了就加上你的要求" to "Leave empty for the default: redraw this one from the project's current state and replace it in place. Or add your requirements",
        "提示词（可不填）" to "Prompt (optional)",
        "派给哪个会话" to "Send to which session",
        "这台机器上还没有会话 —— 先去看板 ＋ 开一个" to "No sessions on this machine yet — open one from the board first",
        "会把一整段任务说明发进那个会话，agent 在服务器上画、用 yxi-lab 推回来。App 里不带任何技能。" to "A full task brief goes into that session; the agent draws on the server and pushes it back with yxi-lab. The app ships no skills.",
        "默认执行" to "Run default",
        "发过去" to "Send",
        "已送进 %s —— 但有 %d 个文件没传上去（%s）" to "Sent to %s — but %d file(s) didn't upload (%s)",
        "%d 个文件已经传上去了，但消息没发出去：%s —— 直接在 App 里发一句就行，文件不用重传" to "%d file(s) uploaded, but the message didn't send: %s — just send it from the app; no need to re-upload the files",
        "没送出去：%s" to "Didn't send: %s",
        "活动中心" to "Events",
        "正在取…" to "Loading…",
        "活动还没开通。开了之后签到、限时活动都在这儿 —— 签到攒的「曦光」拿去祈愿。" to "Events aren't live yet. Once they are, check-ins and limited-time events show up here — Rays earned from checking in go toward wishes.",
        "每日签到" to "Daily check-in",
        "已经连着签了 %d 天" to "%d-day streak",
        "签到中…" to "Checking in…",
        "今天签过了" to "Checked in today",
        "签到" to "Check-in",
        "明天签到给：%s" to "Tomorrow's check-in reward: %s",
        "更多活动还没上。有了会摆在这儿。" to "No more events yet. They'll show up here once there are.",
        "卡牌库" to "Card Library",
        "《神之冠冕》· 已收集 %d / %d" to "Crowns of the Gods · %d / %d collected",
        "祈愿还没开通 —— 下面是全部的样子，都还没获得。" to "Wishing isn't live yet — everything below is a preview; none of it is owned yet.",
        "设定待补" to "Lore coming soon",
        "未获得" to "Not owned",
        "传输中断了" to "Transfer interrupted",
        "还有 %d 个附件在传，传完再发 —— 现在发它们就不在这条消息里了" to "%d attachment(s) still uploading — send once they're done. Sending now means they won't be in this message.",
        "先写点什么，或者加个附件" to "Write something, or add an attachment",
        "线路" to "Line",
        "没换成：%s" to "Switch failed: %s",
        "已换到「%s」· %s\n下一次请求就走新线路；那一次会重读整段对话，慢一点、贵一点，是正常的。" to "Switched to “%s” · %s\nThe next request uses the new line; it re-reads the whole conversation, so it'll be slower and pricier than usual — that's expected.",
        "这台机器上有 %d 个会话在干活 —— 已排队，跑完这一轮自动换。" to "%d session(s) on this machine are working — queued, it'll switch once this round finishes.",
        "没存上：%s" to "Couldn't save: %s",
        "没删掉：%s" to "Couldn't delete: %s",
        "排队中：这一轮跑完就换到「%s」" to "Queued: switching to “%s” once this round finishes",
        "这台机器上有 Codex 会话 —— 它读的是自己那份配置，不跟着线路走，换了要重开。" to "This machine has Codex sessions — they read their own config, not the line. Switch it and they'll need a restart.",
        "取不到 —— 没连上那台机器。" to "Couldn't load — not connected to that machine.",
        "默认（走 Claude Code 自己的登录）" to "Default (uses Claude Code's own sign-in)",
        "不设任何端点和钥匙" to "No endpoint or key set",
        "令牌 " to "Token ",
        "密钥 " to "Key ",
        "什么都没填" to "Nothing set",
        "现在走的不是列表里的任何一条（可能是在电脑上或手动改的）：%s" to "What's live right now isn't any line in this list (maybe set on the machine directly, or edited by hand): %s",
        "只设了钥匙，没设端点" to "Only a key is set — no endpoint",
        "改" to "Edit",
        "+ 加一条线路" to "+ Add a line",
        "加一条线路" to "Add a line",
        "改线路" to "Edit line",
        "名字（自己认得就行）" to "Name (anything you'll recognize)",
        "端点 ANTHROPIC_BASE_URL" to "Endpoint ANTHROPIC_BASE_URL",
        "令牌 ANTHROPIC_AUTH_TOKEN" to "Token ANTHROPIC_AUTH_TOKEN",
        "密钥 ANTHROPIC_API_KEY" to "Key ANTHROPIC_API_KEY",
        "留空的那项会写成空串 —— 那才是「不设」。留空不等于沿用上一条。" to "A blank field is saved as an empty string — that's what “not set” means. Blank doesn't carry over the previous line's value.",
        "存" to "Save",
        "真删？再点一次" to "Really delete? Tap again",
        "删掉" to "Delete",
        "邮件" to "Mail",
        "取不到 —— 网络不通，或者登录过期了。下拉重试或重新登录。" to "Couldn't load — no network, or your sign-in expired. Pull to retry, or sign in again.",
        "还没有信。兑换成功、会员快到期这些会发到这里。" to "No mail yet. Redemption confirmations, membership expiry notices — they land here.",
        "看更早的" to "See earlier",
        "到期" to "Expiry",
        "公告" to "Notice",
        "这张图读不了，换一张" to "Can't read this image — pick another one",
        "点头像换一张 · 只存在这台手机上" to "Tap the avatar to change it · stays on this phone only",
        "会员资料没拉到：" to "Couldn't load your membership info: ",
        "粘贴或输入兑换码" to "Paste or type a redeem code",
        "余额到账" to "Balance added",
        "Welcome to" to "Welcome to",
        "当前余额 ¥%s" to "Current balance ¥%s",
        "会员有效期至 %s" to "Membership valid until %s",
        "这块还没开通。界面先摆在这儿，后台那边定好了就能用 —— 不做点了没反应的假按钮。" to "Not live yet. The screen's already here — it'll work once the backend's ready. We don't ship buttons that do nothing when tapped.",
        "钱包" to "Wallet",
        "充值还没开 · 以后可以用余额自动续会员" to "Top-ups aren't live yet · later your balance can auto-renew membership",
        "读取中" to "Loading",
        "趋势" to "Trends",
        "今天 %s · $%.2f" to "Today %s · $%.2f",
        "每天烧了多少 token、多少钱" to "How many tokens, and how much money, you burn each day",
        "祈愿" to "Wish",
        "正在读这台机器的用量…" to "Reading this machine's usage…",
        "这台机器上没有 ccusage —— 装上它才有按天的用量。\n" to "This machine doesn't have ccusage — install it to see day-by-day usage.\n",
        "（我们不自己数：token 好数，钱要一张随时在变的价目表，抄进 App 就会过期。）" to "(We don't tally this ourselves: tokens are easy to count, but cost needs a price list that keeps changing — copy it into the app and it goes stale.)",
        "token · 美元" to "Tokens · USD",
        "这天用了哪些模型" to "Models used that day",
        "这 %d 天合计" to "%d-day total",
        "《神之冠冕》· %d 位" to "Crowns of the Gods · %d characters",
        "祈愿还没开通。开了之后：签到攒「曦光」，一张曦光换一次祈愿；\n" to "Wishing isn't live yet. Once it is: check in to earn Rays, and one Ray buys one wish;\n",
        "奖池的 UP 是**角色**（第一个是云曦）—— 抽到她会一并带上她的立绘头像、\n" to "the pool's featured pulls are **characters** (the first is Yunxi) — get her and you also get her portrait,\n",
        "专属光环、专属开屏和主题配色。其余是单件装扮，另有少量会员天数。\n" to "her exclusive aura, splash screen, and theme colors. Everything else is a single skin, plus a few days of membership.\n",
        "⚠️ 摇号在服务端，概率会公示 —— 公示的和实际发奖的是同一套数。" to "⚠️ The draw runs on the server, and drop rates are published — what's published is exactly what's used.",
        "%d 抽内必出稀有" to "Guaranteed rare within %d pulls",
        "曦光 ×%d" to "Rays ×%d",
        "离保底还差 %d 抽" to "%d pulls to pity",
        "祈愿 ×%d" to "Wish ×%d",
        "%d 曦光 · 会员九折" to "%d Rays · discounted for members",
        "%d 曦光" to "%d Rays",
        "概率公示" to "Drop rates",
        "已有 · 折 %d 曦光" to "Owned · converts to %d Rays",
        "已有" to "Owned",
        "点一下关闭 · 还剩 %d 张曦光" to "Tap to close · %d Rays left",
        "点一下跳过" to "Tap to skip",
        "曦光" to "Rays",
        "稀有" to "Rare",
        "普通" to "Common",
        // 邮件页：筛选 / 删除（cc-Yxi_Entertainment 2026-09-05）
        "全部" to "All",
        "未读 %d" to "Unread %d",
        "未读" to "Unread",
        "已读" to "Read",
        "没有未读的信" to "No unread mail",
        "没有已读的信" to "No read mail yet",
        "先领取再删" to "Claim it before deleting",
        "删除这封信？" to "Delete this mail?",
        "删了就找不回来了。" to "It can't be recovered.",
        "没删掉 —— 网络不通或登录过期了，信还在。" to "Couldn't delete — no network, or your sign-in expired. The mail is still there.",
    )
}
