package app.yxi.agent

import org.json.JSONObject

/**
 * 线路预设 —— 从 CC Switch 源码 `src/config/{claude,codex}ProviderPresets.ts` 解析出来的（2026-09-05）。
 * 只带**名字 + 端点 + 模型键 + 分类**，钥匙永远要用户自己填。
 *
 * ⚠️ Codex 只收 **原生 Responses 协议**（`openai_responses`）和直连 base_url 的那些；
 *    `openai_chat` 那 23 条要靠 CC Switch 的本地代理转协议，**Yxi 不跑代理**，所以不列 ——
 *    列出来等于承诺一个做不到的事。
 *
 * ⚠️ 表是快照，中转站的地址会变。选了预设之后端点仍然可编辑，出问题以用户填的为准。
 */
object LinePresets {

    class Preset(val name: String, val agent: String, val baseUrl: String, val category: String, val env: Map<String, String> = emptyMap(), val model: String = "") {
        /** 预设里的 env 键（模型映射之类），不含端点和钥匙 */
        fun envJson(): JSONObject = JSONObject().also { o -> env.forEach { (k, v) -> o.put(k, v) } }
    }

    val CLAUDE: List<Preset> = listOf(
        Preset("Kimi", Lines.CLAUDE, "https://api.moonshot.cn/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "kimi-k2.7-code", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "kimi-k2.7-code", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "kimi-k2.7-code", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "kimi-k2.7-code")),
        Preset("Kimi For Coding", Lines.CLAUDE, "https://api.kimi.com/coding/", "cn_official", mapOf("ANTHROPIC_MODEL" to "kimi-for-coding", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "kimi-for-coding", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "kimi-for-coding", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "kimi-for-coding")),
        Preset("PackyCode", Lines.CLAUDE, "https://www.packyapi.ai", "third_party"),
        Preset("ZetaAPI", Lines.CLAUDE, "https://api.zetaapi.ai", "aggregator"),
        Preset("APINebula", Lines.CLAUDE, "https://apinebula.ai", "third_party"),
        Preset("AICodeMirror", Lines.CLAUDE, "https://api.aicodemirror.ai/api/claudecode", "third_party"),
        Preset("PatewayAI", Lines.CLAUDE, "https://api.pateway.ai", "third_party"),
        Preset("FennoAI", Lines.CLAUDE, "https://api.fenno.ai", "aggregator"),
        Preset("RunAPI", Lines.CLAUDE, "https://runapi.host", "aggregator"),
        Preset("Shengsuanyun", Lines.CLAUDE, "https://router.shengsuanyun.com/api", "aggregator", mapOf("ANTHROPIC_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "anthropic/claude-haiku-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "anthropic/claude-opus-5")),
        Preset("AIGoCode", Lines.CLAUDE, "https://api.aigocode.app", "third_party"),
        Preset("Qiniu", Lines.CLAUDE, "https://api.qnaigc.com", "aggregator"),
        Preset("AICoding", Lines.CLAUDE, "https://api.aicoding.inc", "third_party"),
        Preset("SubRouter", Lines.CLAUDE, "https://subrouter.ai", "aggregator"),
        Preset("APIKEY.FUN", Lines.CLAUDE, "https://api.apikey.fun", "third_party"),
        Preset("9527CODE", Lines.CLAUDE, "https://9527.codes", "aggregator"),
        Preset("ClaudeAPI", Lines.CLAUDE, "https://gw.apito.ai", "aggregator"),
        Preset("Code0", Lines.CLAUDE, "https://code0.ai", "aggregator"),
        Preset("TeamoRouter", Lines.CLAUDE, "https://api.teamorouter.cn", "aggregator"),
        Preset("PPIO", Lines.CLAUDE, "https://api.ppio.com/anthropic", "aggregator", mapOf("ANTHROPIC_MODEL" to "deepseek/deepseek-v4-flash-0731", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "deepseek/deepseek-v4-flash-0731", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "deepseek/deepseek-v4-flash-0731", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "deepseek/deepseek-v4-flash-0731")),
        Preset("ClaudeCN", Lines.CLAUDE, "https://claudecn.top", "third_party"),
        Preset("火山 Agent Plan", Lines.CLAUDE, "https://ark.cn-beijing.volces.com/api/plan", "cn_official", mapOf("ANTHROPIC_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "ark-code-latest")),
        Preset("火山 Coding Plan", Lines.CLAUDE, "https://ark.cn-beijing.volces.com/api/coding", "cn_official", mapOf("ANTHROPIC_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "ark-code-latest")),
        Preset("BytePlus", Lines.CLAUDE, "https://ark.ap-southeast.bytepluses.com/api/coding", "cn_official", mapOf("ANTHROPIC_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "ark-code-latest", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "ark-code-latest")),
        Preset("DouBaoSeed", Lines.CLAUDE, "https://ark.cn-beijing.volces.com/api/compatible", "cn_official", mapOf("ANTHROPIC_MODEL" to "doubao-seed-2-1-pro-260628", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "doubao-seed-2-1-pro-260628", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "doubao-seed-2-1-pro-260628", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "doubao-seed-2-1-pro-260628")),
        Preset("SiliconFlow", Lines.CLAUDE, "https://api.siliconflow.cn", "aggregator", mapOf("ANTHROPIC_MODEL" to "Pro/MiniMaxAI/MiniMax-M2.5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "Pro/MiniMaxAI/MiniMax-M2.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "Pro/MiniMaxAI/MiniMax-M2.5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "Pro/MiniMaxAI/MiniMax-M2.5")),
        Preset("SiliconFlow en", Lines.CLAUDE, "https://api.siliconflow.com", "aggregator", mapOf("ANTHROPIC_MODEL" to "MiniMaxAI/MiniMax-M3", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "MiniMaxAI/MiniMax-M3", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "MiniMaxAI/MiniMax-M3", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "MiniMaxAI/MiniMax-M3")),
        Preset("A6API", Lines.CLAUDE, "https://api.a6api.com", "aggregator"),
        Preset("AtlasCloud", Lines.CLAUDE, "https://api.atlascloud.ai", "aggregator", mapOf("ANTHROPIC_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "zai-org/glm-5.1")),
        Preset("Compshare", Lines.CLAUDE, "https://api.modelverse.cn", "aggregator"),
        Preset("Compshare Coding Plan", Lines.CLAUDE, "https://cp.compshare.cn", "aggregator"),
        Preset("CCSub", Lines.CLAUDE, "https://www.ccsub.net", "aggregator"),
        Preset("SSSAiCode", Lines.CLAUDE, "https://node-hk.sssaicodeapi.com/api", "third_party"),
        Preset("Micu", Lines.CLAUDE, "https://www.micuapi.ai", "third_party"),
        Preset("RightCode", Lines.CLAUDE, "https://www.rightapi.ai/claude", "third_party"),
        Preset("ETok.ai", Lines.CLAUDE, "https://api.etok.ai", "third_party"),
        Preset("Cubence", Lines.CLAUDE, "https://api.cubence.com", "third_party"),
        Preset("CrazyRouter", Lines.CLAUDE, "https://cn.crazyrouter.com", "third_party"),
        Preset("DMXAPI", Lines.CLAUDE, "https://www.dmxapi.cn", "aggregator"),
        Preset("SudoCode.chat", Lines.CLAUDE, "https://api.sudocode.chat", "third_party"),
        Preset("SudoCode.us", Lines.CLAUDE, "https://sudocode.us", "third_party"),
        Preset("XycAi", Lines.CLAUDE, "https://apicdn.xycai.us", "aggregator"),
        Preset("Amux", Lines.CLAUDE, "https://api.amux.ai", "aggregator"),
        Preset("Gemini Native", Lines.CLAUDE, "https://generativelanguage.googleapis.com", "third_party", mapOf("ANTHROPIC_MODEL" to "gemini-3.6-flash", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "gemini-3.6-flash", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "gemini-3.6-flash", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "gemini-3.6-flash")),
        Preset("DeepSeek", Lines.CLAUDE, "https://api.deepseek.com/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "deepseek-v4-pro", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "deepseek-v4-flash", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "deepseek-v4-pro", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "deepseek-v4-pro")),
        Preset("OpenCode Go", Lines.CLAUDE, "https://opencode.ai/zen/go", "third_party", mapOf("ANTHROPIC_MODEL" to "deepseek-v4-flash", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "deepseek-v4-flash", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "deepseek-v4-flash", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "deepseek-v4-flash")),
        Preset("Zhipu GLM", Lines.CLAUDE, "https://open.bigmodel.cn/api/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "glm-5.1")),
        Preset("Zhipu GLM en", Lines.CLAUDE, "https://api.z.ai/api/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "glm-5.1", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "glm-5.1")),
        Preset("Baidu Qianfan Coding Plan", Lines.CLAUDE, "https://qianfan.baidubce.com/anthropic/coding", "cn_official", mapOf("ANTHROPIC_MODEL" to "qianfan-code-latest", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "qianfan-code-latest", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "qianfan-code-latest", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "qianfan-code-latest")),
        Preset("Bailian", Lines.CLAUDE, "https://dashscope.aliyuncs.com/apps/anthropic", "cn_official"),
        Preset("Bailian For Coding", Lines.CLAUDE, "https://coding.dashscope.aliyuncs.com/apps/anthropic", "cn_official"),
        Preset("QwenCloud", Lines.CLAUDE, "https://dashscope-intl.aliyuncs.com/apps/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "qwen3.7-max", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "qwen3.6-flash", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "qwen3.7-max", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "qwen3.7-max")),
        Preset("QwenCloud For Coding", Lines.CLAUDE, "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "qwen3.7-plus", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "qwen3.7-plus", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "qwen3.7-plus", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "qwen3.7-plus")),
        Preset("QwenCloud Token Plan", Lines.CLAUDE, "https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "qwen3.8-max", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "qwen3.6-flash", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "qwen3.8-max", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "qwen3.8-max")),
        Preset("StepFun", Lines.CLAUDE, "https://api.stepfun.com/step_plan", "cn_official", mapOf("ANTHROPIC_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "step-3.5-flash-2603")),
        Preset("StepFun en", Lines.CLAUDE, "https://api.stepfun.ai/step_plan", "cn_official", mapOf("ANTHROPIC_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "step-3.5-flash-2603", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "step-3.5-flash-2603")),
        Preset("ModelScope", Lines.CLAUDE, "https://api-inference.modelscope.cn", "aggregator", mapOf("ANTHROPIC_MODEL" to "ZhipuAI/GLM-5.2", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "ZhipuAI/GLM-5.2", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "ZhipuAI/GLM-5.2", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "ZhipuAI/GLM-5.2")),
        Preset("KAT-Coder", Lines.CLAUDE, "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/\${ENDPOINT_ID}/claude-code-proxy", "cn_official", mapOf("ANTHROPIC_MODEL" to "KAT-Coder-Pro V1", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "KAT-Coder-Air V1", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "KAT-Coder-Pro V1", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "KAT-Coder-Pro V1")),
        Preset("Longcat", Lines.CLAUDE, "https://api.longcat.chat/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "LongCat-2.0", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "LongCat-2.0", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "LongCat-2.0", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "LongCat-2.0")),
        Preset("MiniMax", Lines.CLAUDE, "https://api.minimaxi.com/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "MiniMax-M2.7")),
        Preset("MiniMax en", Lines.CLAUDE, "https://api.minimax.io/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "MiniMax-M2.7", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "MiniMax-M2.7")),
        Preset("BaiLing", Lines.CLAUDE, "https://api.tbox.cn/api/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "Ling-2.5-1T", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "Ling-2.5-1T", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "Ling-2.5-1T", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "Ling-2.5-1T")),
        Preset("AiHubMix", Lines.CLAUDE, "https://aihubmix.com", "aggregator"),
        Preset("CherryIN", Lines.CLAUDE, "https://open.cherryin.net", "aggregator", mapOf("ANTHROPIC_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "anthropic/claude-haiku-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "anthropic/claude-opus-5")),
        Preset("RelaxyCode", Lines.CLAUDE, "https://www.relaxycode.com", "third_party"),
        Preset("E-FlowCode", Lines.CLAUDE, "https://e-flowcode.cc", "third_party"),
        Preset("OpenRouter", Lines.CLAUDE, "https://openrouter.ai/api", "aggregator", mapOf("ANTHROPIC_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "anthropic/claude-haiku-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "anthropic/claude-opus-5")),
        Preset("TheRouter", Lines.CLAUDE, "https://api.therouter.ai", "aggregator", mapOf("ANTHROPIC_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "anthropic/claude-haiku-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "anthropic/claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "anthropic/claude-opus-5")),
        Preset("Novita AI", Lines.CLAUDE, "https://api.novita.ai/anthropic", "aggregator", mapOf("ANTHROPIC_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "zai-org/glm-5.1", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "zai-org/glm-5.1")),
        Preset("GitHub Copilot", Lines.CLAUDE, "https://api.githubcopilot.com", "third_party", mapOf("ANTHROPIC_MODEL" to "claude-sonnet-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "claude-haiku-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "claude-sonnet-5")),
        Preset("Codex", Lines.CLAUDE, "https://chatgpt.com/backend-api/codex", "third_party", mapOf("ANTHROPIC_MODEL" to "gpt-5.6-sol", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "gpt-5.6-luna", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "gpt-5.6-sol", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "gpt-5.6-sol")),
        Preset("xAI (Grok)", Lines.CLAUDE, "https://api.x.ai/v1", "third_party", mapOf("ANTHROPIC_MODEL" to "grok-4.5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "grok-4.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "grok-4.5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "grok-4.5")),
        Preset("Nvidia", Lines.CLAUDE, "https://integrate.api.nvidia.com", "aggregator", mapOf("ANTHROPIC_MODEL" to "moonshotai/kimi-k2.5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "moonshotai/kimi-k2.5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "moonshotai/kimi-k2.5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "moonshotai/kimi-k2.5")),
        Preset("PIPELLM", Lines.CLAUDE, "https://cc-api.pipellm.ai", "aggregator", mapOf("ANTHROPIC_MODEL" to "claude-opus-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "claude-haiku-4-5-20251001", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "claude-opus-5")),
        Preset("Xiaomi MiMo", Lines.CLAUDE, "https://api.xiaomimimo.com/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "mimo-v2.5-pro")),
        Preset("Xiaomi MiMo Token Plan (China)", Lines.CLAUDE, "https://token-plan-cn.xiaomimimo.com/anthropic", "cn_official", mapOf("ANTHROPIC_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "mimo-v2.5-pro", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "mimo-v2.5-pro")),
        Preset("AWS Bedrock (AKSK)", Lines.CLAUDE, "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com", "cloud_provider", mapOf("ANTHROPIC_MODEL" to "global.anthropic.claude-opus-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "global.anthropic.claude-haiku-4-5-20251001-v1:0", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "global.anthropic.claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "global.anthropic.claude-opus-5")),
        Preset("AWS Bedrock (API Key)", Lines.CLAUDE, "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com", "cloud_provider", mapOf("ANTHROPIC_MODEL" to "global.anthropic.claude-opus-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "global.anthropic.claude-haiku-4-5-20251001-v1:0", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "global.anthropic.claude-sonnet-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "global.anthropic.claude-opus-5")),
        Preset("JieKou AI", Lines.CLAUDE, "https://api.jiekou.ai/anthropic", "aggregator", mapOf("ANTHROPIC_MODEL" to "claude-fable-5", "ANTHROPIC_DEFAULT_HAIKU_MODEL" to "claude-fable-5", "ANTHROPIC_DEFAULT_SONNET_MODEL" to "claude-fable-5", "ANTHROPIC_DEFAULT_OPUS_MODEL" to "claude-fable-5")),
        Preset("AICodeWith", Lines.CLAUDE, "https://api.aicodewith.ai", "aggregator"),
    )

    val CODEX: List<Preset> = listOf(
        Preset("PackyCode", Lines.CODEX, "https://www.packyapi.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("ZetaAPI", Lines.CODEX, "https://api.zetaapi.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("APINebula", Lines.CODEX, "https://apinebula.ai/v1", "third_party", model = ""),
        Preset("AICodeMirror", Lines.CODEX, "https://api.aicodemirror.ai/api/codex/backend-api/codex", "third_party", model = "gpt-5.6-sol"),
        Preset("PatewayAI", Lines.CODEX, "https://api.pateway.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("FennoAI", Lines.CODEX, "https://api.fenno.ai", "third_party", model = "gpt-5.6-sol"),
        Preset("RunAPI", Lines.CODEX, "https://runapi.host/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Shengsuanyun", Lines.CODEX, "https://router.shengsuanyun.com/api/v1", "third_party", model = "openai/gpt-5.6-sol"),
        Preset("AIGoCode", Lines.CODEX, "https://api.aigocode.app", "third_party", model = "gpt-5.6-sol"),
        Preset("Qiniu", Lines.CODEX, "https://api.qnaigc.com/bypass/openai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("AICoding", Lines.CODEX, "https://api.aicoding.inc", "third_party", model = "gpt-5.6-sol"),
        Preset("SubRouter", Lines.CODEX, "https://subrouter.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("APIKEY.FUN", Lines.CODEX, "https://api.apikey.fun/v1", "third_party", model = ""),
        Preset("9527CODE", Lines.CODEX, "https://9527.codes/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Code0", Lines.CODEX, "https://code0.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("TeamoRouter", Lines.CODEX, "https://api.teamorouter.cn/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("ClaudeCN", Lines.CODEX, "https://claudecn.top/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("火山 Agent Plan", Lines.CODEX, "https://ark.cn-beijing.volces.com/api/plan/v3", "third_party", model = "ark-code-latest"),
        Preset("火山 Coding Plan", Lines.CODEX, "https://ark.cn-beijing.volces.com/api/coding/v3", "third_party", model = "ark-code-latest"),
        Preset("BytePlus", Lines.CODEX, "https://ark.ap-southeast.bytepluses.com/api/coding/v3", "third_party", model = "ark-code-latest"),
        Preset("DouBaoSeed", Lines.CODEX, "https://ark.cn-beijing.volces.com/api/v3", "third_party", model = "doubao-seed-2-1-pro-260628"),
        Preset("A6API", Lines.CODEX, "https://api.a6api.com/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Compshare", Lines.CODEX, "https://api.modelverse.cn/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Compshare Coding Plan", Lines.CODEX, "https://cp.compshare.cn/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("CCSub", Lines.CODEX, "https://www.ccsub.net/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("SSSAiCode", Lines.CODEX, "https://node-hk.sssaicodeapi.com/api/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Micu", Lines.CODEX, "https://www.micuapi.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("RightCode", Lines.CODEX, "https://www.rightapi.ai/codex/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("ETok.ai", Lines.CODEX, "https://api.etok.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Cubence", Lines.CODEX, "https://api.cubence.com/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("CrazyRouter", Lines.CODEX, "https://cn.crazyrouter.com/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("DMXAPI", Lines.CODEX, "https://www.dmxapi.cn/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("SudoCode.chat", Lines.CODEX, "https://api.sudocode.chat/v1", "third_party", model = ""),
        Preset("SudoCode.us", Lines.CODEX, "https://sudocode.us/v1", "third_party", model = ""),
        Preset("XycAi", Lines.CODEX, "https://apicdn.xycai.us/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("Amux", Lines.CODEX, "https://api.amux.ai/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("DeepSeek", Lines.CODEX, "https://api.deepseek.com", "third_party", model = "deepseek-v4-flash"),
        Preset("Zhipu GLM", Lines.CODEX, "https://open.bigmodel.cn/api/v1", "third_party", model = "glm-5.3"),
        Preset("Zhipu GLM en", Lines.CODEX, "https://api.z.ai/api/v1", "third_party", model = "glm-5.3"),
        Preset("Bailian", Lines.CODEX, "https://dashscope.aliyuncs.com/compatible-mode/v1", "third_party", model = "qwen3-coder-plus"),
        Preset("QwenCloud", Lines.CODEX, "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", "third_party", model = "qwen3.7-max"),
        Preset("QwenCloud Token Plan", Lines.CODEX, "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1", "third_party", model = "qwen3.8-max"),
        Preset("Tencent Hunyuan", Lines.CODEX, "https://tokenhub.tencentmaas.com/v1", "third_party", model = "hy3"),
        Preset("Longcat", Lines.CODEX, "https://api.longcat.chat/openai/v1", "third_party", model = "LongCat-2.0"),
        Preset("MiniMax", Lines.CODEX, "https://api.minimaxi.com/v1", "third_party", model = "MiniMax-M3"),
        Preset("MiniMax en", Lines.CODEX, "https://api.minimax.io/v1", "third_party", model = "MiniMax-M3"),
        Preset("Xiaomi MiMo", Lines.CODEX, "https://api.xiaomimimo.com/v1", "third_party", model = "mimo-v2.5-pro"),
        Preset("Xiaomi MiMo Token Plan (China)", Lines.CODEX, "https://token-plan-cn.xiaomimimo.com/v1", "third_party", model = "mimo-v2.5-pro"),
        Preset("xAI (Grok)", Lines.CODEX, "https://api.x.ai/v1", "third_party", model = "grok-4.5"),
        Preset("AiHubMix", Lines.CODEX, "https://aihubmix.com/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("CherryIN", Lines.CODEX, "https://open.cherryin.net/v1", "third_party", model = "openai/gpt-5.6-sol"),
        Preset("RelaxyCode", Lines.CODEX, "https://www.relaxycode.com/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("E-FlowCode", Lines.CODEX, "https://e-flowcode.cc/v1", "third_party", model = ""),
        Preset("PIPELLM", Lines.CODEX, "https://cc-api.pipellm.ai/v1", "third_party", model = ""),
        Preset("OpenRouter", Lines.CODEX, "https://openrouter.ai/api/v1", "third_party", model = "gpt-5.6-sol"),
        Preset("TheRouter", Lines.CODEX, "https://api.therouter.ai/v1", "third_party", model = "openai/gpt-5.3-codex"),
        Preset("AICodeWith", Lines.CODEX, "https://api.aicodewith.ai/chatgpt/v1", "third_party", model = "gpt-5.6-sol"),
    )

    fun forAgent(agent: String) = if (agent == Lines.CODEX) CODEX else CLAUDE
}
